[Experimental] Enable git hooks for code validation and setup test suite
FreeTubeApp/FreeTube pull request #1171
Opened 2021-04-07 09:47 UTC by lambdaclan

---
Title
---
Implement various qol features for improving code quality.

**Pull Request Type**

Experimental (discussion needed before merging upstream)

**Related issue**

N/A

**Special note**
I feel sad about having to even add this section but you never know who will be reading this so here it goes. All the "criticisms" mentioned below are made **in good faith** and in an attempt to point out the issues with the current setup so that we can improve the application we all use and care about. I made an effort to use constructive comments in a heartfelt, meaningful tone that does not imply criticism towards the maintainers and any contributors.

**Description**

Currently the project does not include an automated way to ensure that the code being committed and pushed upstream is validated against the measures we have in place such as ESLint and Prettier. Furthermore, although the project does have some checks in place the code overall is not in a valid state. It will take time and effort to make all files pass the checks so we need to make sure that it stays like that and that new additions do not change the status.

![prettier_errors](https://user-images.githubusercontent.com/47409392/113833220-5cb9d980-97c4-11eb-8cef-1e2b0caa5089.png)

![eslint_errors](https://user-images.githubusercontent.com/47409392/113833251-65121480-97c4-11eb-933a-2d0b0c68d611.png)

Linting, formatting and testing make more sense when run before committing/pushing code. By doing so we ensure no errors ever make it into the repository and maintain a consistent coding style for the multiple contributors working on the project regardless of the  editors and IDEs they use. It will also speed up the PR process since the checks run by the CI should be green by default leaving more time for the maintainers to look into what actually matters the code changes without having to worry about styling and linting errors.

The check for either tool can be run manually but that can complicate things because the scripts will run the checks on the whole codebase rather than just the files that are staged in git. This can actually be disruptive, running a lint process on the whole project can be slow, linting/formatting results can be irrelevant to the work being done and the number of flagged files can be overwhelming putting people off from running the checks in the first place. We need a better way to run checks only on files that will be committed.

To continue with, the existing GitHub action workflows only check for linting errors but do not perform any formatting checks although the setup is already in place.

Beyond the topic of code styling checks and their automation the project currently does not have a test suite or any tests for that matter. I will not discuss the merits of software testing since I have already established (through the project's communication channels) that we are in agreement that a test suite for FreeTube is indeed desired. Having a testing framework in place will encourage authoring of tests for at least all new code and will hopefully spark an interest to go back and test the existing code as well.

Looking a bit further into the future, having tests that we can trust and rely on will allow us to better prepare for what I am assuming will inevitably happen down the road, the switch to Vue 3 and TypeScript. Those are quite big topics that will require a lot of effort and refactoring so any help we can get would be beneficial.

 **Feature list**
 
This PR aims to tackle the issues mentioned above as follows:

- [x] create a testing environment setup for unit and end to end (e2e) testing
- [x] incorporate git hooks that automatically run ESLint and Prettier before each commit only on staged files and run all tests before each push
- [x] adjust continuous integration to include format checks and test suite runner
- [x] add additional checks that can improve code quality and style (import sorting order)
- [x] initiate the discussion of how we can further improve the structure and organization of the project as a whole  
 
 **Tools and frameworks**
 
 - Git hooks
     - [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks) was chosen over alternatives such as [husky](https://github.com/typicode/husky) and [pre-commit](https://github.com/pre-commit/pre-commit) because is simple to setup and is lightweight.
     - simple-git-hooks is also the recommended hook management tool to be used alongside [lint-staged](https://github.com/okonet/lint-staged), (for more info see [here](https://github.com/okonet/lint-staged/pull/954)) which is what I used to run the validation checks only on files staged in git. lint-staged is also [recommended by Prettier](https://prettier.io/docs/en/precommit.html#option-1-lint-stagedhttpsgithubcomokonetlint-staged) for automation purposes.
     - Both simple-git-hooks and lint-staged can be configured via config files (`.simple-git-hooks.json` and `.lintstagedrc.json`) which make adjustments fairly trivial.
     - simple-git-hooks automatically generate the git hooks after `npm install` through a post install script.
     - checks can bypassed via the no `[--no-verify`](https://git-scm.com/docs/githooks#_pre_commit) flag which is why we still need the checks to run in CI.

 -  Testing 
     - Regarding information for testing Vue applications the [official documentation](https://v3.vuejs.org/guide/testing.html#frameworks) provides all the necessary information. Note that the information for Vue 2 and 3 is largely the same. I went through the documentation, played with the various tools mentioned and picked what I felt made more sense.
     - [Jest](https://lambdaclan.github.io/) was the chosen test runner tool and unit testing for the following reasons:
         - it is already included in the dev dependencies of the project
         - it is the first recommendation by the Vue official documentation
         - it is "batteries included" with all necessary tools used in testing such as assertions and mocking
         - it works well and is the recommended testing tool to be used with the chosen component testing library (details mentioned below)
    - For component testing there are only two options. [Vue Testing Library](https://testing-library.com/docs/vue-testing-library/intro) and [Vue Test Utils](https://vue-test-utils.vuejs.org/). After trying out both, I settled with Vue Testing library for the following reasons:
        - it is newer and is built on top of Vue Test Utils, the official testing library for Vue which means most of the the features available in that library are still available plus a lot more (they hide some on purpose, please see [here](https://testing-library.com/docs/vue-testing-library/faq))
        - it re-exports query utilities and helpers from DOM Testing Library emulating querying the DOM in the same way the user would making tests more accessible and easier to write
        - it works hand in hand with [Jest custom DOM matchers](https://github.com/testing-library/jest-dom#readme)
        - their [guiding principles](https://testing-library.com/docs/guiding-principles/) are in line with how I feel testing should be done
        - it has nice, easy to understand documentation
	- For end to end testing the Vue official documentation mostly talks about web based applications with cross-browser testing which currently does not apply to FreeTube therefore the recommended tools were not considered. As FreeTube is Electron based the choice was easy as there are not many e2e testing frameworks for Electron apps. [Spectron](https://www.electronjs.org/spectron) is the recommended framework by the Electron official documentation and although Mocha seems to be the recommended testing framework (https://github.com/electron-userland/spectron#usage) the documentation clearly states that "Spectron works with any testing framework" and can verify that it works just as good with Jest.

- General QOL additions
    -  A [...]

2021-09-18 12:33 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Hi @lambdaclan Please update us about this. Is this ready for review?

2021-09-25 13:09 UTC, ChunkyProgrammer requested changes
We switched to yarn for dependency insallation so you'll have to use `npm run ci` instead of `npm ci`

2021-09-25 13:09 UTC, ChunkyProgrammer commented on .github/workflows/ci.yml
> +  NODE_VERSIONS: [12.x]
```suggestion
  NODE_VERSIONS: [14.x]
```

2021-09-25 13:09 UTC, ChunkyProgrammer commented on .github/workflows/ci.yml
> +        run: npm ci
```suggestion
        run: npm run ci
```

2021-09-25 13:09 UTC, ChunkyProgrammer commented on .github/workflows/ci.yml
> +        run: npm ci
```suggestion
        run: npm run ci
```

2021-09-25 13:09 UTC, ChunkyProgrammer commented on .github/workflows/ci.yml
> +        run: npm ci
```suggestion
        run: npm run ci
```

2021-09-25 13:09 UTC, ChunkyProgrammer commented on .github/workflows/ci.yml
> +        run: npm ci
```suggestion
        run: npm run ci
```

2021-09-29 07:18 UTC, PikachuEXE commented
For me I would 
- start small (less hooks, probably just running lint on commit at the beginning)
- use `lefthook` 
  (but waiting for [next release with fix on hook script and maybe a performance boost](https://github.com/evilmartians/lefthook/issues/233#issuecomment-929411864) before I submit a draft PR)

2021-09-29 10:27 UTC, ChunkyProgrammer commented on package.json
>      "prettier": "prettier --write \"{src,_scripts}/**/*.{js,ts,vue}\"",
```suggestion
    "prettier": "prettier --check \"{src,_scripts}/**/*.{js,ts,vue}\"",
```

2021-10-05 17:17 UTC, ChunkyProgrammer commented
Closing PR in favor of #1788

2021-10-05 17:17 UTC, closed without merging