* Update main process to handle all opened windows on some setting change
FreeTubeApp/FreeTube pull request #1203
Opened 2021-04-16 05:26 UTC by PikachuEXE

**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
Follow up change for #1153

**Description**
In #1153 some settings change does not apply on all opened windows
This PR's change would ensure the following settings are applied to all opened windows
- smooth scrolling enabled (by closing all opened windows instead of just the "main" window)
- proxy URL (by applying the proxy setting to all opened windows instead of just the "main" window)

**Screenshots (if appropriate)**
(Not Applicable)

**Testing (for code that is not small enough to be easily understandable)**
"Smooth scrolling": opening multiple windows via the button introduced in #1153, update "smooth scrolling enabled", all windows are closed and a new window reopened
"Proxy URL": NOT tested (No idea how to inspect proxy value of a window visually)

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.7
 - FreeTube version: 12.0.0 (latest on `development` actually)

**Additional context**
(Not Applicable)

2021-04-20 06:01 UTC, PikachuEXE commented
Added a fix for an issue that might be introduced due to #1153

`var === null` cannot handle `undefined` but `var == null` can

2021-04-27 16:37 UTC, Svallinn requested changes
Nice work.
However, there's one big problem with this PR.

Technically speaking, the windows are successfully letting each other know when the proxy setting changes, but only the windows are aware of it, the store state isn't.
So what ends up happening is that if the proxy is turned off and you turn it on in one window

![image](https://user-images.githubusercontent.com/41585298/116278245-d7e42f00-a775-11eb-986c-e5a33090f8c3.png)

Every other windows' settings will look like this

![image](https://user-images.githubusercontent.com/41585298/116278314-e92d3b80-a775-11eb-92cc-8572e05cead1.png)

because their store states weren't updated. The same applies if the host or port number were to be changed.
So you'll need to implement an ipc call that can handle that and propagate every other window when the proxy settings change.

Of course, this most likely applies to **every other setting** that we have, so making it as generic as possible now so that we can cover every other setting in the future would be ideal.

2021-04-27 16:37 UTC, Svallinn commented on src/main/index.js
> +    if (mainWindow == null) {
Either use simplified checking
```js
if (mainWindow) {
```
Or use strict equality, even if it's more verbose
```js
if (mainWindow === null || mainWindow === undefined) {
```

2021-04-29 08:14 UTC, PikachuEXE commented
I simply give up on multi-window state sync
For this PR I will just include the fix for new window no opened when all window closed on MacOS

2021-04-29 20:51 UTC, merged