+ Add Reload Video button on video page
FreeTubeApp/FreeTube pull request #1223
Opened 2021-04-22 08:14 UTC by PikachuEXE

**Pull Request Type**
Please select what type of pull request this is:
- [X] Feature Implementation

**Related issue**
https://github.com/FreeTubeApp/FreeTube/issues/1005

**Description**
Adds a button to view video page, next to share button (can be repositioned)
Which reload the view/page actually on click

**Screenshots (if appropriate)**
![image](https://user-images.githubusercontent.com/1018543/115679816-8b6bae80-a385-11eb-907f-16a2e9cac750.png)

**Testing (for code that is not small enough to be easily understandable)**
- View a video 
- Press the new button

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.7
 - FreeTube version: 12.0.0 (latest on `development` actually)

2021-04-27 15:40 UTC, Svallinn requested changes
As far as I can tell, this doesn't actually work.
It's trying to refresh the page rather than reload the components.
So it ends up like this after clicking the button.
![image](https://user-images.githubusercontent.com/41585298/116270680-d5caa200-a76e-11eb-828b-82f933cb5fb7.png)

2021-07-01 16:40 UTC, peepopoggers commented
yeah reloading breaks components, not sure y

2021-07-06 15:35 UTC, jcartner-young commented
IMHO a 'reload button' feels like a bit of a workaround for some unresolved problems laying beneath.

Maybe build some logic into the play button to deal with these 'disconnections' in the background?

Or,  as a last resort, initiate the reload routine when this error occurs, with a counter so after 3 tries it can fail with an error?

Likely need to find out what is causing the error to start with - TCP/server/session timeout? TCP/Session keep-alive??

2021-07-07 01:51 UTC, PikachuEXE commented
@jcartner-young 

Agree
I think the current workaround (reloading) is good enough as a workaround and this is no much better (and it's not working)

2021-07-07 01:51 UTC, closed without merging