* Implement playlist countdown per second
FreeTubeApp/FreeTube pull request #1234
Opened 2021-04-28 06:26 UTC by PikachuEXE

**Pull Request Type**
Please select what type of pull request this is:
- [X] Feature Implementation

**Related issue**
https://github.com/FreeTubeApp/FreeTube/issues/1214

**Description**
Instead of just showing "Playing next video in N seconds. Click ..." 1 time
Show that message with remaining of seconds until cancelled or jumped to next video
See attached video

**Screenshots (if appropriate)**
Countdown without cancel
https://user-images.githubusercontent.com/1018543/116199247-7d44d600-a769-11eb-9790-c4a394d0d361.mp4

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.7
 - FreeTube version: 12.0.0 (latest on `development` actually)

2021-04-28 06:33 UTC, PikachuEXE commented
Note: 
The logic in this PR would cause it to NOT display "Playing next video in no time"
Code comment with explanation added

2021-04-28 13:51 UTC, Svallinn requested changes
LGTM. Just make the small change I suggested and I'll merge it.

2021-04-28 13:51 UTC, Svallinn commented on src/renderer/views/Watch/Watch.js
> +          countDownTimeLeftInMs = countDownTimeLeftInMs - 1000
This variable is completely unnecessary.
You can just use `countDownTimeLeftInSecond` in the conditional logic above.

2021-04-29 02:14 UTC, PikachuEXE commented
Requested change made

2021-04-29 16:57 UTC, Svallinn approved these changes

2021-04-29 16:58 UTC, merged