Translate window titles
FreeTubeApp/FreeTube pull request #1321
Opened 2021-05-23 18:32 UTC by ChunkyProgrammer

---
Translate window titles
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
closes #1310 

**Description**
- Setting the document title was moved to the "Views" (Translations could not be done directly in router, router instead passes a key as the title)
- Both Channels & Profile Settings didn't have a good translation string for the title:
   - For channel, I changed it to become the channel's name followed by " - FreeTube" because video's were doing video name followed by " - FreeTube"
   - For Profile Settings, I added a new translation string to en-US and en-GB

**Screenshots (if appropriate)**
Title when viewing Adam Neely's YT channel:
![image](https://user-images.githubusercontent.com/78101139/119270915-1b8f5480-bbcd-11eb-9ec4-29013b544dc5.png)

Title when viewing "Subscriptions" (French):
![image](https://user-images.githubusercontent.com/78101139/119270951-3bbf1380-bbcd-11eb-9f24-9f2b4184854a.png)

Title when viewing "About" (French):
![image](https://user-images.githubusercontent.com/78101139/119270966-56918800-bbcd-11eb-934e-0a2281339fcc.png)

Title when viewing "History" (French):
![image](https://user-images.githubusercontent.com/78101139/119271008-86d92680-bbcd-11eb-9760-9c91bc8c5468.png)

Title when viewing "Settings" (French):
![image](https://user-images.githubusercontent.com/78101139/119271178-707f9a80-bbce-11eb-947f-e462e917c1e8.png)

Title when viewing "User Playlists" (French):
![image](https://user-images.githubusercontent.com/78101139/119271188-7b3a2f80-bbce-11eb-9f6f-5db6730503c9.png)

**Testing (for code that is not small enough to be easily understandable)**
Change "locale" in settings and navigate to different pages

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13
 
**Additional context**
Titles don't get updated when using the "Forward" & "Backwards" navigation (this is the case in the current release of FreeTube though)

2021-05-24 01:21 UTC, ChunkyProgrammer commented
- Go to trending
- Go to a channel
- Click 'Back' button
- Title = "[object Object]"
I think this is caused by 'Channel' in router getting passed to 'Trending' .
This is an issue with the title not being properly updated on forwards/backwards navigation, however which I feel like should be a separate issue

2021-05-26 21:34 UTC, ChunkyProgrammer commented on src/renderer/views/About/About.js
> +    document.title = `${this.$t(this.$route.meta.title)} - ${process.env.PRODUCT_NAME}`
Changing this.$route.meta.title to "About.About" and repeating for all other cases should fix the window not being properly updated when back button is pressed. Thoughts?

2021-05-28 23:38 UTC, ChunkyProgrammer commented
Ok, I am now happy with how this feature turned out. (it is no longer hacky and bad). Let me know if there's anything that should be changed.

2021-07-21 14:32 UTC, PrestonN requested changes
Looks good to me for the most part. Please make this one change and then I'm good to merge.

2021-07-21 14:32 UTC, PrestonN commented on src/renderer/router/index.js
> +        title: 'ProfileEdit',
This needs to be `Profile.Edit Profile`

2021-07-21 15:09 UTC, ChunkyProgrammer commented on src/renderer/router/index.js
> +        title: 'ProfileEdit',
fixed

2021-07-21 15:44 UTC, PrestonN commented
LGTM. Thank you!

2021-07-21 15:45 UTC, merged