Improve search filter appearance
FreeTubeApp/FreeTube pull request #1360
Opened 2021-05-28 06:02 UTC by PikachuEXE

**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
#1337

**Description**
Update search filter style so it's smaller in size and has 10% transparency

**Screenshots (if appropriate)**
https://user-images.githubusercontent.com/1018543/119937349-32fb8280-bfbd-11eb-84b6-188895103df4.mp4

**Testing (for code that is not small enough to be easily understandable)**
- Open filter
- Keep resizing the window

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.7
 - FreeTube version: 13.0.0 (latest on `development` actually)

**Additional context**
Add any other context about the problem here.

2021-06-14 16:55 UTC, Svallinn requested changes

2021-06-14 16:55 UTC, Svallinn commented on src/renderer/components/ft-search-filters/ft-search-filters.vue
>    <div class="searchFilter">
Remove the class from this `div` and from the CSS file, as it will no longer be used for anything.

2021-06-15 07:10 UTC, PikachuEXE commented
Updated

2021-06-15 14:20 UTC, Svallinn requested changes

2021-06-15 14:20 UTC, Svallinn commented on src/renderer/components/ft-search-filters/ft-search-filters.css
>  .searchFilter {
You still left the class here -_-'

2021-06-15 14:53 UTC, merged