Add video reload button
FreeTubeApp/FreeTube pull request #1578
Opened 2021-08-11 13:04 UTC by jasonhenriquez

---
Add video reload button
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
closes #1005 

**Description**
This PR introduces a reload button to force re-render of the video player component as a convenient workaround for assorted infrequent video player issues.

**Screenshot & Video**
![Screenshot of the video page featuring the new video reload button.](https://user-images.githubusercontent.com/84899178/129032693-29d1f46b-faae-476c-94c8-62c939ada881.png)

Here is a short video showcasing the video reload button:
https://user-images.githubusercontent.com/84899178/129032258-c14a5fbe-da5a-411e-a4a5-4852e52bf9e0.mp4

**Testing (for code that is not small enough to be easily understandable)**
Pressed the reload button on three videos with DASH, Legacy, and Audio formats (three clicks each).

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.13.2 Beta

2021-08-12 09:19 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Looks nice just one question why did u chose that spot for the reload button instead of next to the star button or the share button?

2021-08-12 09:51 UTC, jasonhenriquez commented
@efb4f5ff-1298-471a-8973-3d47447115dc The button initiates a page reload, which I thought was disruptive enough to warrant visually distinguishing it. It should not be much work for me to change that, though, so I welcome the dev team's feedback on that.

2021-08-16 17:50 UTC, peepopoggers commented
I dont really like the placement of the button

2021-08-16 17:57 UTC, jasonhenriquez commented
@peepopoggers That's fair. What would be a good place in your opinion? I had previously considered the top right of the video rectangle, somewhere near the "Up Next" heading, and to the immediate right of the 'Subscribe' button.

2021-08-16 19:04 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
maybe do it browser style? I know its only for reloading the video and not its not system wide, but it looks familiar.
![Capture](https://user-images.githubusercontent.com/73130443/129616216-f8a0446c-8945-4be9-a6dc-634ea4026bf1.PNG)

2021-08-16 23:21 UTC, jasonhenriquez commented
> 
> 
> maybe do it browser style? I know its only for reloading the video and not its not system wide, but it looks familiar.

I think this could work well, but I have qualms about placing it next to the arrow keys for a couple reasons. As @jcartner-young says, that's leaning into browser UI territory unnecessarily. The other reason is that it's difficult to notice in that location. Maybe just to the right of the FreeTube icon at the top?

> also maybe change the icon to this?
> https://fontawesome.com/v5.15/icons/redo-alt?style=solid

Good idea, I will switch it out with that.

2021-08-16 23:37 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> I think this could work well, but I have qualms about placing it next to the arrow keys for a couple reasons. As @jcartner-young says, that's leaning into browser UI territory unnecessarily. The other reason is that it's difficult to notice in that location. Maybe just to the right of the FreeTube icon at the top?

I agree with ur points but seems a bit out of place to have an icon to the right FT logo.

> @efb4f5ff-1298-471a-8973-3d47447115dc The button initiates a page reload, which I thought was disruptive enough to warrant visually distinguishing it. 

Hmm what about only showing the icon on the video player page in the location i suggested. So the reload button will be gone if u lets say search for videos. It will only be present next to the arrows if it is on the player page.

2021-08-21 07:31 UTC, jasonhenriquez commented
> Hmm what about only showing the icon on the video player page in the location i suggested. So the reload button will be gone if u lets say search for videos. It will only be present next to the arrows if it is on the player page.

Implemented in 0e5ff8c.

2021-08-31 03:58 UTC, PikachuEXE requested changes
Can it restart at the current timestamp?
I am copying the YT URL with timestamp and paste on top nav bar as current workaround.

2021-08-31 10:59 UTC, jasonhenriquez commented
> Can it restart at the current timestamp?
> I am copying the YT URL with timestamp and paste on top nav bar as current workaround.

It is supposed to maintain the current timestamp, and still does on my device after testing, although you do have to wait until it has loaded. If you click it once and then click it again while the video is still loading, the timestamp will go away. I can fix this through throttling if need be (I made a fix with a nice waiting animation locally a couple of weeks ago that I will conjure up again). Is this the issue you are experiencing, or does the timestamp never get saved? Note: I think there are specific issues with your development setup, so try testing it as a build (`npm run build` on the branch and then test with that build).

2021-09-01 02:57 UTC, PikachuEXE commented
I am now using the built app via `npm run build`
But reloading still makes the video play from the beginning
Let me take a look at the code and see if any tweak can be added

2021-09-01 03:05 UTC, PikachuEXE commented
Clarifying what I expect:
a) If I paste a URL in navbar (e.g. https://www.youtube.com/watch?v=VekMorjnRuk&list=PLzFTGYa_evXjIHj3YW0Xp5PiVzjpd-IBG&t=136)
Load the video, let it play a few seconds (e.g. `140`) and press reload, it reloads to `136` in URL
But I expect it to reload to `140`
b) If I paste a URL without timestamp
Load the video, let it play a few seconds (e.g. `5`) and press reload, it reloads to `0`
But I expect it to reload to `5`

2021-09-09 22:02 UTC, ChunkyProgrammer commented on src/renderer/views/Watch/Watch.js
> +    console.log('a')
This line should probably be removed

2021-09-10 03:35 UTC, PikachuEXE commented
I just re-read the description of this PR:
> This PR introduces a reload button to force re-render of the video player component as a convenient workaround for assorted infrequent video player issues.

If I remember it correctly the issue would be video getting "stuck" after a long time of pause and unable to continue playing the rest of content.
If this is the issue this PR is trying to workaround, then the video should be started playing at "current timestamp" (the time before reload) instead of from the beginning / the time from video URL.

2021-09-10 03:43 UTC, PikachuEXE commented
Reloading from current timestamp can be done via this diff:
```diff
diff --git a/src/renderer/views/Watch/Watch.js b/src/renderer/views/Watch/Watch.js
index 61c29c29..6c7e9555 100644
--- a/src/renderer/views/Watch/Watch.js
+++ b/src/renderer/views/Watch/Watch.js
@@ -219,10 +219,14 @@ export default Vue.extend({
       this.useTheatreMode = !this.useTheatreMode
     },
     forceVideoPlayerRerender: function() {
+      const currentTimestampBeforeReload = this.timestamp
+
       this.beforeLeave()
       this.$refs.videoPlayer.beforeLeave()
       this.videoPlayerIndex++
       this.route()
+      // Restart playing the video at the timestamp before reload
+      this.changeTimestamp(currentTimestampBeforeReload)
     },
     getVideoInformationLocal: function() {
       if (this.firstLoad) {

```

Preview:

https://user-images.githubusercontent.com/1018543/132795841-652d8703-f4fc-4a74-8c78-39677fe7fe27.mov

2021-09-10 03:52 UTC, jasonhenriquez commented
> then the video should be started playing at "current timestamp" (the time before reload) instead of from the beginning / the time from video URL.

Again, the former behavior is already working for me locally. But if it is not working on your device, I will probably implement your solution or something similar.

2021-09-10 13:24 UTC, peepopoggers commented
Looks good. Also, an idea - do you think the refresh should update subscriptions / other pages as well as refreshing the page? (like the circle reload button already does)

2021-09-10 13:32 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
The plan is the rework the reload button. All other refresh buttons will be removed and the refresh button will be applied globally trough the application instead of only on the videoplayer page.

2021-09-10 13:38 UTC, jasonhenriquez commented
> The plan is the rework the reload button. All other refresh buttons will be removed and the reload button will be applied globally through the application instead of only on the videoplayer page.

Yes, I have been busy recently but will be working on this soon.

2021-09-10 13:40 UTC, peepopoggers commented
@efb4f5ff-1298-471a-8973-3d47447115dc Okay, that sounds good.

2021-09-17 21:07 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
I'll mark this with "Changes requested" label because its going to be reworked.

2023-01-11 17:45 UTC, sQur1 commented
Can this button show up on the subscriptions tab too? Thanks

2023-01-11 18:47 UTC, ChunkyProgrammer commented
> Can this button show up on the subscriptions tab too? Thanks

There should already be a button on the subscriptions tab

2023-01-11 18:56 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> The plan is the rework the reload button. All other refresh buttons will be removed and the reload button will be applied globally through the application instead of only on the videoplayer page.

@sQur1 please search the conversation before asking

2023-08-26 06:30 UTC, closed without merging