Channel view layout issue
FreeTubeApp/FreeTube pull request #1591
Opened 2021-08-16 13:11 UTC by JInfantesC

---
Channel view layout issue 
---

**Pull Request Type**
- [X] Bugfix
- [ ] Feature Implementation

**Related issue**
Closes #1499

**Description**
This request modifies the CSS and HTML layout the channel view

**Screenshots (if appropriate)**

![](https://user-images.githubusercontent.com/7262829/124974861-d7d99880-e01c-11eb-9252-5a2f984a1d3a.png)

![](https://user-images.githubusercontent.com/7262829/124974868-da3bf280-e01c-11eb-862b-b0c783aeb59f.png)

![](https://user-images.githubusercontent.com/7262829/124974882-dc9e4c80-e01c-11eb-8f5f-baa709e27679.png)

**Testing (for code that is not small enough to be easily understandable)**
Only CSS and HTML changes.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - OS Version: 21.04
 - FreeTube version: Release 0.13.2 Beta

2021-08-16 17:41 UTC, peepopoggers approved these changes

2021-08-16 22:14 UTC, ChunkyProgrammer requested changes

2021-08-17 17:00 UTC, peepopoggers commented on src/renderer/views/Channel/Channel.vue
> +            style="align-self: center"
Fixed

2021-08-17 17:00 UTC, peepopoggers commented on src/renderer/views/Channel/Channel.vue
> +            <div style="display: flex;justify-content: center;flex-direction: column;padding-left: 1em;">
Fixed

2021-08-17 17:00 UTC, peepopoggers commented on src/renderer/views/Channel/Channel.vue
> +          <div style="display:flex">
Fixed

2021-08-17 17:02 UTC, peepopoggers approved these changes
Made a few edits and is approved.

2021-08-17 17:18 UTC, ChunkyProgrammer approved these changes

2021-08-17 17:18 UTC, ChunkyProgrammer commented
LGTM

2021-08-17 17:42 UTC, peepopoggers approved these changes

2021-08-17 22:05 UTC, jasonhenriquez approved these changes
LGTM!

2021-08-18 02:35 UTC, PrestonN approved these changes

2021-08-18 02:46 UTC, PrestonN approved these changes

2021-08-18 02:52 UTC, PrestonN approved these changes

2021-08-18 02:59 UTC, PrestonN approved these changes

2021-08-18 03:09 UTC, PrestonN approved these changes

2021-08-18 03:13 UTC, PrestonN approved these changes

2021-08-18 03:14 UTC, PrestonN approved these changes

2021-08-18 03:16 UTC, PrestonN approved these changes

2021-08-18 15:42 UTC, peepopoggers approved these changes

2021-08-18 15:59 UTC, PrestonN approved these changes

2021-08-19 20:24 UTC, ChunkyProgrammer approved these changes

2021-08-19 20:25 UTC, PrestonN approved these changes

2021-08-19 21:01 UTC, PrestonN approved these changes

2021-08-19 21:08 UTC, PrestonN approved these changes

2021-08-19 21:29 UTC, PrestonN approved these changes

2021-08-19 21:33 UTC, PrestonN approved these changes

2021-08-19 21:36 UTC, PrestonN approved these changes

2021-08-19 21:41 UTC, PrestonN approved these changes

2021-08-19 21:48 UTC, PrestonN approved these changes

2021-08-20 01:18 UTC, PrestonN approved these changes

2021-08-20 01:21 UTC, PrestonN approved these changes

2021-08-20 01:25 UTC, PrestonN approved these changes

2021-08-20 01:37 UTC, PrestonN approved these changes

2021-08-20 01:55 UTC, PrestonN approved these changes

2021-08-20 01:57 UTC, PrestonN approved these changes

2021-08-20 02:00 UTC, PrestonN approved these changes

2021-08-20 18:54 UTC, merged