Update top nav input box action button icon depends on input
FreeTubeApp/FreeTube pull request #1738
Opened 2021-09-23 07:13 UTC by PikachuEXE

**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
It's [a comment/feedback in another PR](https://github.com/FreeTubeApp/FreeTube/pull/1669#issuecomment-918015016)

**Description**
Before: Top nav input box action button icon is always "arrow right"
After: Action button icon changes depend on input text "looks like a youtube URL" or not
- Looks like YT URL: icon = "arrow right"
- Otherwise: icon = "search"

**Screenshots (if appropriate)**
Too lazy to make video
![Screenshot 2021-09-23 at 3 04 46 PM](https://user-images.githubusercontent.com/1018543/134467373-62469cb2-e6de-42e6-accb-0310a13a39e2.png)
![Screenshot 2021-09-23 at 3 04 30 PM](https://user-images.githubusercontent.com/1018543/134467362-312f197c-8252-46a7-84f3-ecf6bd4c9fee.png)

**Testing (for code that is not small enough to be easily understandable)**
- Enter Youtube URLs (e.g. Video, Playlist, Channel), look at icon changed
- Clear text via different methods after Youtube URLs entered
- Enter non Youtube URLs (any text)
- Clear text via different methods after text entered

**Desktop (please complete the following information):**
- OS: MacOS
- OS Version: 11.6
- FreeTube version: based on b1a310ef09cdad6f2eda5b65a544e5b2e0880648

**Additional context**
Add any other context about the problem here.

2021-09-23 16:00 UTC, peepopoggers requested changes
Tested this locally and it works great.
In my opinion it should accept all URL's for it to display arrow as this does not account for invidious links / future additions.

2021-09-24 03:25 UTC, PikachuEXE commented
I now instead updated it to use `getYoutubeUrlInfo`
And update the icon according to the `urlType`

### Example URLs 

#### Video with Playlist
- https://www.youtube.com/watch?v=_qmCjsIU2fc&list=PLzFTGYa_evXjIHj3YW0Xp5PiVzjpd-IBG
- https://yewtu.be/watch?v=_qmCjsIU2fc&list=PLzFTGYa_evXjIHj3YW0Xp5PiVzjpd-IBG

#### Playlist
- https://youtube.com/playlist?list=PLzFTGYa_evXjrYYxeY6HAQyqnkJju2t84
- https://yewtu.be/playlist?list=PLzFTGYa_evXjrYYxeY6HAQyqnkJju2t84

#### Channel
- https://www.youtube.com/channel/UCz7eke4JGlbtc11_6mmA7ew
- https://yewtu.be/channel/UCz7eke4JGlbtc11_6mmA7ew

#### Search (Only Youtube URL supported by FT now)
- https://www.youtube.com/results?search_query=pikachu

2021-09-24 03:44 UTC, jasonhenriquez commented on src/renderer/components/ft-input/ft-input.js
> +            }
```suggestion
            case 'video':
            case 'playlist':
            case 'search':
            case 'channel':
              isYoutubeLink = true
              break
            case 'hashtag':
              // TODO: Implement a hashtag related view
              // isYoutubeLink is already `false`
              break
```

2021-09-24 06:20 UTC, PikachuEXE commented
@jasonhenriquez 
Updated

2021-09-24 09:16 UTC, peepopoggers commented
What about youtube shorts?

2021-09-24 09:18 UTC, PikachuEXE commented
@peepopoggers 
Is it supported by YT now?
I am only following `getYoutubeUrlInfo` here

2021-09-24 09:22 UTC, peepopoggers commented
Test this:
https://www.youtube.com/shorts/MS82yTaKRjQ?feature=share

2021-09-24 09:22 UTC, peepopoggers commented
#1605

2021-09-24 09:23 UTC, PikachuEXE commented
https://www.youtube.com/shorts/MS82yTaKRjQ?feature=share
This PR seems working
![image](https://user-images.githubusercontent.com/1018543/134651381-069a7287-7cea-42a1-b81c-be38d15eafad.png)

2021-09-24 09:37 UTC, peepopoggers submitted a review, later dismissed
:+1:

2021-09-27 01:58 UTC, PikachuEXE commented
"Update action button to look & act as disabled when input text is empty"

https://user-images.githubusercontent.com/1018543/134834657-3931df76-608a-4af7-91d6-7cccc3561600.mov

@jasonhenriquez

2021-09-27 02:21 UTC, ChunkyProgrammer commented on src/renderer/components/ft-input/ft-input.css
> +}
```suggestion
  cursor: unset;
}
```

2021-09-27 02:23 UTC, ChunkyProgrammer commented
Maybe unset the background color on hover & active when disabled as well?

2021-09-27 03:41 UTC, PikachuEXE commented
Get 1 more person to agree with you and it will be done
I am not sure if removing those effect would have negative effect on UX

2021-09-27 12:00 UTC, peepopoggers commented
@ChunkyProgrammer can you explain what these changes you would propose would do in more detail?

2021-09-27 12:12 UTC, ChunkyProgrammer commented
> @ChunkyProgrammer can you explain what these changes you would propose would do in more detail?

Sure,
If the search bar is empty then I think the search icon shouldn't react to css events like hovering and activated as the search functionality is disabled at that point. If you test the PR and click on the search icon, there's a visual indication that you clicked on (background-color changes) which gives the impression (to me at least) of the search being successful even if search is disabled.

2021-09-27 12:30 UTC, peepopoggers commented
Okay, I agree with that functionality as searching for nothing does not make much sense.

2021-09-27 14:27 UTC, jasonhenriquez commented
I second that.

2021-09-28 03:54 UTC, PikachuEXE commented
Updated

https://user-images.githubusercontent.com/1018543/135020667-2bc8c733-bd8f-4dd3-9890-d785dbd23d8a.mov

2021-09-28 16:35 UTC, ChunkyProgrammer commented on src/renderer/components/ft-input/ft-input.css
>    cursor: pointer;
I'd move this line to .inputAction.enabled (line 100)

2021-09-29 02:20 UTC, PikachuEXE commented
@ChunkyProgrammer 
Updated

https://user-images.githubusercontent.com/1018543/135192108-4b95c0e0-abd3-43f4-b50b-d44e6d0c3742.mov

2021-09-30 04:33 UTC, peepopoggers approved these changes
LGTM

2021-09-30 19:28 UTC, ChunkyProgrammer approved these changes

2021-10-01 00:18 UTC, PikachuEXE commented
1 more to go!

2021-10-01 07:38 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
Press B, LGTM!

2021-10-01 07:38 UTC, merged

2021-10-01 10:51 UTC, PikachuEXE commented
@efb4f5ff-1298-471a-8973-3d47447115dc 
You want to cancel the merge!?