Dev/githook
FreeTubeApp/FreeTube pull request #1788
Opened 2021-10-04 07:29 UTC by PikachuEXE

**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
Smaller version of #1171

**Description**
- Add git hook via `lefthook`
- Installing `lefthook` via `npm`/`yarn` will generate git hook scripts in your git hook path
  (By default it's `.git/hooks`, by default **not** version controlled on purpose, which can be changed via [`core.hooksPath`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corehooksPath)
- Add a `pre-commit` hook to run `eslint` on every commit which lints staged (about to be committed) files only (faster) where the filenames end with `js/ts/vue`

For all available hook events and other stuff about Git Hooks see:
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Screenshots (if appropriate)**
Code Change Diff (for testing linting)
![Screenshot 2021-10-04 at 3 27 02 PM](https://user-images.githubusercontent.com/1018543/135810449-fb157f64-22a7-4788-92dc-d2fb7147a1e8.png)

Git output
![image](https://user-images.githubusercontent.com/1018543/135810498-c772a76b-4500-4340-b141-c20bc0d02e7e.png)

**Testing (for code that is not small enough to be easily understandable)**
- Make change(s) violating any lint rule
- Commit those changes

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 11.6
 - FreeTube version: based on 84ac98f0a33c8ca450019c6ea7d43abd02c2fb2c

**Additional context**
Add any other context about the problem here.

2021-11-23 09:47 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed
LGTM

2022-06-22 11:14 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2022-06-23 09:56 UTC, absidue requested changes

2022-06-24 01:26 UTC, PikachuEXE commented on lefthook.yml
> +      run: npx eslint --no-color {staged_files}
(Unrelated to this PR)
Do you think we should also replace other `npm run` in CI to yarn?

2022-06-24 01:26 UTC, PikachuEXE commented
All requested changes in https://github.com/FreeTubeApp/FreeTube/pull/1788#pullrequestreview-1016722307 made

2022-06-24 21:42 UTC, absidue approved these changes

2022-06-24 22:03 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-06-25 05:04 UTC, PikachuEXE commented
@ChunkyProgrammer ~

2022-08-11 20:46 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@ChunkyProgrammer one more approval needed. Review if u have some spare time please

2022-08-12 03:41 UTC, ChunkyProgrammer commented
No idea how I missed the notifications for this one. This looks good to me. I'll approve it now. (There are newer versions of lefthook available so maybe it should be upgraded soon?)

2022-08-12 03:41 UTC, ChunkyProgrammer approved these changes

2022-08-12 03:41 UTC, merged

2022-08-12 04:24 UTC, PikachuEXE commented
Crap I forgot to update the lefthook version