Automatically compile to arm64 when running on apple silicon and hide FreeTube user agent
FreeTubeApp/FreeTube pull request #1888
Opened 2021-11-12 08:20 UTC by Arctic26

---
Automatically compile to arm64 when running on apple silicon and hide FreeTube user agent
---
**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Description**
- Automatically selects arm64 architecture when building on an apple chip
- Change the default user agent to hide that freetube is being used

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 12.0.1
 - FreeTube version: 0.15.1

2021-11-12 09:20 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
U need to change branch to development

2021-11-18 07:29 UTC, PikachuEXE requested changes
User agent change should be reverted

2021-11-18 07:29 UTC, PikachuEXE commented on src/main/index.js
> +    newWindow.webContents.userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" // Prevent youtube from seeing the fre
I am not sure if we should set a custom user agent
Even if we do it should be an option (or at least not a constant value for all OS)

I think this should be reverted

2021-11-18 07:47 UTC, PikachuEXE requested changes

2021-11-18 07:47 UTC, PikachuEXE commented on _scripts/build.js
> +  }
Remove trailing commas, set default value...
```suggestion
  let arch = Arch.x64

  if (cpus[0].model.startsWith('Apple')) {
    arch = Arch.arm64
  }

  targets = Platform.MAC.createTarget(['dmg'], arch)
```

2021-11-26 02:08 UTC, PikachuEXE requested changes
I have tested `_scripts/build.js` changes locally and the built binary seems running fine and reported as "Apple"

![image](https://user-images.githubusercontent.com/1018543/143516191-d008e5d0-d34b-494d-935c-63f7627cc6c8.png)

However we would only accept that change in this PR and not the custom user agent options
Please submit those changes in a separate PR

2022-05-18 14:05 UTC, closed without merging