Feature: A new way to subscribe
FreeTubeApp/FreeTube pull request #1934
Opened 2021-12-06 16:25 UTC by minhhang107

---
New way to subscribe
---

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
Closes #1615 
Closes #568

**Description**
Added ft-subscribe-button component
- The component includes the existing `Subscribe` button and a `plus` button
- The `plus` button allows users to to select the profile they want to add the subscription to
- Replace the existing `Subscribe` button with the new component in video page and channel page
- If users try to add subscription to the same profile twice, show a toast message

**Screenshots (if appropriate)**
Before:

![before-video](https://user-images.githubusercontent.com/55411709/144881343-99a3c9aa-f7bf-4067-a169-2fc47669e6af.jpg)

![before-channel](https://user-images.githubusercontent.com/55411709/144881376-5e500e4c-9c59-4d9e-ba86-23453b1bb366.jpg)

After:
![after-video](https://user-images.githubusercontent.com/55411709/144881405-4e89ba01-b917-4768-a793-6d9087ceb3f1.png)

![after-channel](https://user-images.githubusercontent.com/55411709/144881413-fa7f2ec0-8ce6-4e16-bfac-b09d85eceae5.jpg)

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Yes

Please describe shortly how you tested it and whether there are any ramifications remaining:
Tested locally on dev by adding/removing channels to/from different profiles using the existing `Subscribe` button and the new button, tested on both video page and channel page

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 0.15.1

2021-12-08 20:57 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@PrestonN idea time!

Maybe we can also do something like this when the playlist is implemented. So u can save a video in playlist in profile x while being in profile y

2021-12-09 15:29 UTC, minhhang107 commented
@efb4f5ff-1298-471a-8973-3d47447115dc The same thing can be done with playlist. Users can also add a video to multiple playlists in another profile. So what do you think about this PR? Are there anything that need to be fixed?

2021-12-09 17:16 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
I didn't had time to test in depth but initial thoughts about it that it is pretty well implemented

Would like to see #1833 mergerd before this one

2021-12-15 10:20 UTC, ChunkyProgrammer commented on src/renderer/components/ft-subscribe-button/ft-subscribe-button.vue
> +      <ft-button
An aria-label or title attribute should be added to this element for accessibility reasons

2022-02-21 13:44 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> I didn't had time to test in depth but initial thoughts about it that it is pretty well implemented
> 
> Would like to see #1833 merged before this one

#1833 has been merged. Please address the changes that have been requested and resolve the merge conflicts in order for us to review.

2022-05-23 11:35 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
- I cant unsubscribe both on the video page and channel page. The same is for subscribing.

https://user-images.githubusercontent.com/73130443/169809748-355822fb-50fd-4737-a635-063996402700.mp4

- There is no dynamic way to unsubscribe now. I would like to see both a '-' and a '+' button . If u click on the '-' u'll see all profiles that have been subscribed to this channel and the ability to remove them. If u click on the '+' u'll get all the profiles that aren't subscribed to the channel and the ability to subscribe to the channel by clicking on the profile icon. So that means when i subscribe to a channel using the '+' list it will remove itself from the '+' list and add itself to the '-' list.

2022-05-24 15:07 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
Im sorry @ChunkyProgrammer for this big spam

https://user-images.githubusercontent.com/73130443/170069147-dfc3e4b7-d8df-4c7f-b78d-47566b0f9f52.mp4


https://user-images.githubusercontent.com/73130443/170069153-ebb2da94-53dc-4e0c-b1cc-b06b57059326.mp4


https://user-images.githubusercontent.com/73130443/170069155-bbd633ab-61d3-4287-8de1-e050ee05ab90.mp4


https://user-images.githubusercontent.com/73130443/170069160-36bbf33a-c379-4222-909d-8305cdc58c8d.mp4


https://user-images.githubusercontent.com/73130443/170069161-cbcb2096-4643-498a-b35e-d3b09ae0f67e.mp4


https://user-images.githubusercontent.com/73130443/170069163-a6162c10-3d06-4402-838c-8fe23179b88d.mp4

![spacing needs to be the same](https://user-images.githubusercontent.com/73130443/170069194-4190182e-6e7e-477d-8ee4-39790c069b5b.PNG)
![dropdown needs more padding](https://user-images.githubusercontent.com/73130443/170069198-aef8bec4-5a32-4e71-9297-8ecff296f41a.PNG)
![weirdWhiteSquare](https://user-images.githubusercontent.com/73130443/170069201-d8d1af2e-a1ba-4228-bd34-639e4d69aa4f.PNG)

2022-05-24 16:33 UTC, ChunkyProgrammer commented
Things to fix:
Channel grid takes up 5 or 4

Not sure:
Dropdown obscures other elements: I think the dropdown is supposed to obscure the other elements?

Not to fix:
"Unsubscribe functionality doesn't match original functionality":  this is actually the intended functionality. There is an error with the code in the dev branch that prevents this from happening (it should be activeProfile._id instead of activeProfile) https://github.com/FreeTubeApp/FreeTube/blob/a5585afa18314cd4757b4a63a47c21cb3a9afc02/src/renderer/views/Channel/Channel.js#L563

2022-05-24 16:38 UTC, ChunkyProgrammer commented
@efb4f5ff-1298-471a-8973-3d47447115dc could you test the grid thing again?

2022-05-24 17:06 UTC, ChunkyProgrammer commented
> > @efb4f5ff-1298-471a-8973-3d47447115dc could you test the grid thing again? (i didn't reproduce it)
> 
> @ChunkyProgrammer I have a big brain fart. Which video/picture we talking about?

This one
https://user-images.githubusercontent.com/73130443/170069153-ebb2da94-53dc-4e0c-b1cc-b06b57059326.mp4

2022-05-30 22:12 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> channel.with.same.name.cant.add.channel.mp4

Fixed
> Channelspace.moves.from.5.to.4.mp4

Fixed
> dropdown.closes.everytime.u.add.channel.mp4

Fixed
> dropdown.obscures.other.elements.mp4


Not sure if we should fix this. More discussion needed.
> unsubscribe.functionality.doesnt.match.the.original.functionality.mp4

unrelated to this PR

> wrong.icon.mp4

fixed
> 
> ![spacing needs to be the same](https://user-images.githubusercontent.com/73130443/170069194-4190182e-6e7e-477d-8ee4-39790c069b5b.PNG) 

Fixed
>![dropdown needs more padding](https://user-images.githubusercontent.com/73130443/170069198-aef8bec4-5a32-4e71-9297-8ecff296f41a.PNG) 

Fixed
>![weirdWhiteSquare](https://user-images.githubusercontent.com/73130443/170069201-d8d1af2e-a1ba-4228-bd34-639e4d69aa4f.PNG)

This isnt fixed and didnt explain it well.

https://user-images.githubusercontent.com/73130443/171063698-516329ae-c0fb-4f58-893e-6d23558feeca.mp4

2022-06-03 13:42 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@ChunkyProgrammer do you think that this closes https://github.com/FreeTubeApp/FreeTube/issues/2213?

2022-06-06 15:21 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed
LGTM!

2022-06-08 01:51 UTC, PikachuEXE requested changes
Code side only small changes required
Feature review to be done later...

2022-06-08 01:51 UTC, PikachuEXE commented on src/renderer/components/ft-subscribe-button/ft-subscribe-button.vue
> +      v-if="showProfiles==='subscribed'"
I think it becomes much easier to read when there is spacing
```suggestion
      v-if="showProfiles === 'subscribed'"
```

2022-06-08 01:51 UTC, PikachuEXE commented on src/renderer/components/ft-subscribe-button/ft-subscribe-button.vue
> +      v-if="showProfiles==='unsubscribed'"
```suggestion
      v-if="showProfiles === 'unsubscribed'"
```

2022-06-08 01:57 UTC, PikachuEXE commented
We do need some document to describe this new feature
Also the tooltips need to be shown faster

### Details
I see empty box if I have no other profiles... (and already subscribed)
I know there is tooltip but they show a few seconds later and I don't think many people would notice it
(It's still fine as is given it's explained well)
![image](https://user-images.githubusercontent.com/1018543/172514311-9a24ec82-e1cb-4d15-8517-f63ca68cae4f.png)

Same for profile full name tooltips
![image](https://user-images.githubusercontent.com/1018543/172514515-b7f7b236-5997-4d99-841a-44f452048261.png)

2022-07-16 09:23 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> I see empty box if I have no other profiles... (and already subscribed)

After looking at this again i do agree it is a bit weird when u see this for the first time. Maybe we can put a text in the box.

For when u click on the + button 'All profiles are subscribed to this channel. If u want to remove this channel from a profile click on - button' and the opposite text for when u click on the - button.

We could also disable the button when there is nothing more to add and show a toast message. Only giving this option because the first option i gave could be problematic with CSS on smaller screens

2022-08-03 02:08 UTC, PikachuEXE commented
I am not sure if this only requires a better documentation to explain it (plus the improvements of course)
Or also an option to only show these buttons when the new option is enabled (kind of advanced feature, with link to documentation)

2022-10-12 01:03 UTC, PikachuEXE commented
My points still stand

2022-10-12 03:29 UTC, ChunkyProgrammer commented
> My points still stand

I only resolved merge conflicts, didn't do any fixing

2022-10-12 04:13 UTC, PikachuEXE commented
@ChunkyProgrammer 
I know ar~
Only for the record (I got goldfish memory)

2022-10-12 06:53 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> Only for the record (I got goldfish memory)

A @PikachuEXE  that behaves like Misty's Psyduck

2023-01-07 20:11 UTC, toby63 commented
One question: will or is this also possible in the playlist menu?
Right now I have a large number of videos saved in the playlist on profile x and I would like to be able to transfer some of the videos to other profiles, without clicking on them first.

Also a way to choose multiple videos and "copy" them to another profile would be nice.

2023-01-24 00:13 UTC, ChunkyProgrammer commented
Outstanding issues: (copying for easier reference as github is hiding this by default)
We do need some document to describe this new feature
Also the tooltips need to be shown faster

### Details
I see empty box if I have no other profiles... (and already subscribed)
I know there is tooltip but they show a few seconds later and I don't think many people would notice it
(It's still fine as is given it's explained well)
![image](https://user-images.githubusercontent.com/1018543/172514311-9a24ec82-e1cb-4d15-8517-f63ca68cae4f.png)

Same for profile full name tooltips
![image](https://user-images.githubusercontent.com/1018543/172514515-b7f7b236-5997-4d99-841a-44f452048261.png)

2023-01-24 01:32 UTC, ChunkyProgrammer commented
I believe I've addressed the concerns

2023-01-24 03:54 UTC, PikachuEXE commented
Is it possible to disable the new buttons (plus & minus) by default?
I think we need better doc before we make it enabled by default

2023-01-26 12:02 UTC, ChunkyProgrammer commented
@PikachuEXE what do you think needs to be documented in order to get this implemented?

2023-01-26 12:35 UTC, PikachuEXE commented
1. Where do those new buttons do (and any subsequent events like press profile to add to that profile etc.)
2. When and where do they appear (they don't appear in subscribed channels view) (Do they still appear always or only in some conditions? I haven't tested again since last review. But it's unclear without testing which is why it should be documented)

2023-01-26 12:57 UTC, ChunkyProgrammer commented
> 1. Where do those new buttons do (and any subsequent events like press profile to add to that profile etc.)
> 2. When and where do they appear (they don't appear in subscribed channels view) (Do they still appear always or only in some conditions? I haven't tested again since last review. But it's unclear without testing which is why it should be documented)

1) any suggestions on how to more clearly indicate that?
2) it's now a part of the SubscribedChannel view (this component should replace all subscribe buttons)

2023-03-14 20:15 UTC, ChunkyProgrammer commented
IIRC, @absidue you said you'd like to implement this differently. Do you think this PR should be updated to just be a subscribe button component so we don't have to repeat the code + logic>

2023-10-27 13:33 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Closing in favor of https://github.com/FreeTubeApp/FreeTube/pull/4238

2023-10-27 13:33 UTC, closed without merging