Feature/channels page
FreeTubeApp/FreeTube pull request #2129
Opened 2022-03-15 08:37 UTC by hockerschwan

Title
---

**Pull Request Type**
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
Closes #1506
#2066

**Description**
Subscribed channels list (similar to ft-profile-channel-list)
Filtering
Sync multiple windows

**Screenshots (if appropriate)**
<img src="https://user-images.githubusercontent.com/80553357/158335874-3d498526-4f33-49bf-b496-3d616933fcd6.PNG" width=480>

**Testing (for code that is not small enough to be easily understandable)**
Manually adding/deleting channels

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version: 21H1
 - FreeTube version: 0.16.0

**Additional context**
Feedbacks appreciated ( spacing / size / wording etc.)
Reminder: rewrite ` thumbnailURL` when #1783 is implemented.

2022-03-15 10:58 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
I think it better to move the channels tab icon to the top of the channels list on the sidebar because channels already has a dedicated section

2022-03-15 11:00 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
I'll mark this with WIP because i'd like to see #1783 merged first

2022-06-03 14:49 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> Reminder: rewrite thumbnailURL when #1783 is implemented.

@hockerschwan #1783 has been merged

2022-06-13 02:45 UTC, hockerschwan commented
added update thumbnail and unsubscribe prompt

>I think it better to move the channels tab icon to the top of the channels list on the sidebar because channels already has a dedicated section

it looks ... out of place
![z21](https://user-images.githubusercontent.com/80553357/173269658-06f14375-76c9-4b99-ac97-4dd7b49c25ee.PNG)

2022-06-19 21:41 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes

2022-06-19 21:41 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on static/locales/en-US.yaml
> +  Unsubscribe Prompt: Are you sure you want to unsubscribe "$"?
change to Are you sure you want to unsubscribe from "$"?

2022-06-20 14:46 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
Last thing before approving. If list is empty hide the search bar. Just like it is implemented in the playlist and history page

2022-06-20 16:15 UTC, hockerschwan commented
done

2022-06-20 16:23 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
lgtm!

2022-07-06 18:23 UTC, GilgusMaximus approved these changes

2022-07-07 06:39 UTC, PikachuEXE reviewed
Code review done
Give me some time to do local feature review...

2022-07-08 03:40 UTC, PikachuEXE approved these changes

2022-07-08 03:40 UTC, merged

2022-07-08 20:41 UTC, toby63 commented
Thx for implementing this, but could you add one more thing?
A way to optionally disable the channel list on the sidebar.

2022-07-08 21:00 UTC, absidue commented
@toby63 That was already in FreeTube before this PR: Distraction Free Settings -> Hide Active Subscriptions

2022-07-08 21:29 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@absidue maybe @toby63 means disabling the channels tab in the sidebar?

2022-07-08 22:54 UTC, toby63 commented
@absidue Thx, somehow I overlooked it, even though I was checking twice :sweat_smile:.