Restore subtitle player setting
FreeTubeApp/FreeTube pull request #2173
Opened 2022-04-08 11:47 UTC by vallode

---
Restore subtitle player setting
---

**Pull Request Type**
- [*] Feature Implementation

**Related issue**
Closes #62 

**Description**
Restores a setting in the player settings section for enabling subtitles/captions on by default

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian
 - OS Version: [e.g. 22] 11
 - FreeTube version: [e.g. 0.8] 0.16.0

**Additional context**
I disabled the setting by default because I think it's better not to confuse users with subtitles always being on before going through the settings.

2022-04-08 18:22 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
1. Could u move the setting beneath Display Play Button In Video Player. I think that is a better place for it.

2. While testing on this (https://youtu.be/J6KeGIWZWJgIf) video i discovered that if it cant find the language it will default to the first one in the array and in this case that is Afrikaans. I dont think it is very useful to the user to display a subtitle that is not their language. We could do a few thing to address this. Check if there is auto generated captions available in that language, if that is not available dont turn on captions on that video. 

3. if we implement 2 then i think its fair to put a warning next to the toggle. Subtitles will only be shown when available in your language.

4. Testing on this video https://youtu.be/MkjPvfCSoWI. set ur language to deutsch > go to video > u only see one type of caption (german autogenerated) > change language to spanish > go to video > check captions > see that it generated a new spanish caption

2022-06-05 08:55 UTC, vallode commented
@absidue @PikachuEXE if you could see above and comment that'd be great :)

2022-06-06 01:55 UTC, PikachuEXE commented
I think the logic for caption options generation is outside of this PR (I think it's done in `transformAndInsertCaptions`)

2022-06-08 12:31 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Currently i'm trying to find captions on videos for all our locales to test out.

2022-09-10 16:45 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@vallode wanted to test this but keeps spitting out annoying errors. Could u merge your branch with latest dev branch

2022-10-27 02:12 UTC, closed without merging