Hide filter on history and playlist page when page is empty
FreeTubeApp/FreeTube pull request #2177
Opened 2022-04-08 16:52 UTC by absidue

---
Hide filter on history and playlist page when page is empty
---

**Pull Request Type**

- [x] Feature Implementation

**Related issue**
Closes #2174 

**Description**
Hides the search bar on history and playlist pages when they pages are empty

**Screenshots (if appropriate)**

_Playlists:_
![before playlists](https://user-images.githubusercontent.com/48293849/162486125-ef895340-ae24-4182-b311-81d74a509901.png)
![after playlists](https://user-images.githubusercontent.com/48293849/162486442-9828a7aa-b13d-4bd3-afe2-0714cf016a7f.png)

_History:_
![before history](https://user-images.githubusercontent.com/48293849/162486262-cf7a3b0b-fe95-49ea-8a9c-3ad5da4cc878.png)
![after history](https://user-images.githubusercontent.com/48293849/162486547-d1f7517a-2173-45f1-a8bc-cda7d1b55da8.png)

**Testing (for code that is not small enough to be easily understandable)**
I tested this by adding and removing videos from the playlists and watching and removing items from the watch history.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 06a7298ded743c1db59f6b946ed038f996bd3340

2022-04-08 17:11 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
```
Check warning on line 18 in src/renderer/views/History/History.vue
GitHub Actions / lint
src/renderer/views/History/History.vue#L18
Attribute "v-show" should go before "@input"
```
```


Check warning on line 25 in src/renderer/views/UserPlaylists/UserPlaylists.vue
GitHub Actions / lint
src/renderer/views/UserPlaylists/UserPlaylists.vue#L25
Attribute "v-show" should go before "@input"
```

2022-04-08 17:23 UTC, absidue commented
Linter issues fixed.

2022-04-08 17:24 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
LGTM! Thank You!

2022-04-09 19:41 UTC, PrestonN approved these changes
LGTM

2022-04-09 19:42 UTC, merged