Browser extension warning
FreeTubeApp/FreeTube pull request #2210
Opened 2022-04-20 13:27 UTC by efb4f5ff-1298-471a-8973-3d47447115dc

---
Browser extension warning
---

**Description**
Added a warning about why u may not want to install this browser extension

**Additional information**
Also added it to the docs https://github.com/FreeTubeApp/FreeTube-Docs/pull/21

2022-04-24 02:34 UTC, 0x6e656b6f commented
You can also change the extension recommendation from Privacy Redirect to LibRedirect since the former is not actively maintained anymore.

2022-04-24 07:41 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> You can also change the extension recommendation from Privacy Redirect to LibRedirect since the former is not actively maintained anymore.

See https://github.com/FreeTubeApp/FreeTube/issues/2089#issuecomment-1046118597

2022-04-24 07:43 UTC, 0x6e656b6f commented
> > You can also change the extension recommendation from Privacy Redirect to LibRedirect since the former is not actively maintained anymore.
> 
> See [#2089 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/2089#issuecomment-1046118597)

? Their [last commit](https://github.com/libredirect/libredirect/commit/4765cebc7dc221e4a2c461efd53292d43f81e53a) is two hour ago.

2022-05-27 01:45 UTC, PikachuEXE approved these changes

2022-05-27 10:26 UTC, absidue requested changes

2022-05-27 10:26 UTC, absidue commented on README.md
> +Disclamer: Learn more about why a browser extension is bad for your [privacy](https://www.privacyguides.org/browsers/#extensions).
```suggestion
Disclaimer: Learn more about why a browser extension is bad for your [privacy](https://www.privacyguides.org/browsers/#extensions).
```

2022-05-27 10:48 UTC, absidue approved these changes

2022-05-28 02:00 UTC, PikachuEXE approved these changes
It's never a good PR without typo 😆

2022-05-29 20:51 UTC, ChunkyProgrammer approved these changes

2022-05-29 20:51 UTC, merged