Format Invidious playlist dates with the selected locale
FreeTubeApp/FreeTube pull request #2244
Opened 2022-05-16 18:46 UTC by absidue

---
Format Invidious playlist dates with the selected locale
---

**Pull Request Type**

- [x] Feature Implementation

**Description**

Currently FreeTube used the dateFormat function provided by the https://github.com/felixge/node-dateformat dependency to format the date for playlists when the Invidious API is selected as a backend. It does a good job of formatting the date however it doesn't respect the users selected locale, to fix this we can use the `Date.prototype.toLocaleDateString()` function that is built into JavaScript. The only downside is that we loose the ordinals (e.g. `9th` -> `9`).

**Screenshots (if appropriate)**

I used German for the screenshots as the difference is clearly visible on the screenshots, it works with the other locales as well, I just didn't screenshot them.

before with the locale set to German:

![before_german](https://user-images.githubusercontent.com/48293849/168660594-01df0e1c-8048-4be9-9568-ae7b8caf749a.jpg)

after with the locale set to German:

![after_german](https://user-images.githubusercontent.com/48293849/168660611-8d477a00-2e49-4d99-945c-271c246a6ad2.jpg)

after with the locale set to English US:

![after_en_us](https://user-images.githubusercontent.com/48293849/168660620-36ddd056-b446-4109-bb34-dd642afe2b2b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 85bbffaf6c25b89f666df4cefee81bb456f03dc1

2022-05-21 12:10 UTC, PikachuEXE submitted a review, later dismissed

2022-05-21 13:38 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
cant test because i got rate limited on the Invidious API -.-

But i saw something interesting with the local api. the language of the date was shown based on the ip address of the country im in. So if my sever is in Germany the date in the description will be German instead of the language i set in the settings.

2022-05-22 12:25 UTC, absidue commented
@efb4f5ff-1298-471a-8973-3d47447115dc Select a different Invidious instance, most of them failed for me too while testing these changes but eventually (took more than 10 tries) I managed to get lucky enough that FreeTube picked an instance that was working.

The issue with the local API is unrelated but i'll try to fix it in the pull request as well. ytpl allows you to set the location and the language, FreeTube currently sets the location, i'll change it so sets the language instead.

2022-05-22 14:03 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
LGTM!

2022-05-22 14:44 UTC, absidue commented
Actually FreeTube does set the language but it does it wrongly, YouTube wants the locale to be `en-GB` but for some reason FreeTube replaces the `-` with an `_` which means FreeTube sends `en_GB` to YouTube, which YouTube sees as an invalid locale so YouTube chooses the locale based on the IP address.

While checking that I also noticed that FreeTube doesn't pass the chosen location on to YouTube (search, playlists and videos) so not sure why that setting is there unless it was just never full implemented.

2022-05-22 14:49 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Do u want me to create an issue for this so we can merge over this PR. Or would u rather fix it in this PR?

2022-05-22 14:51 UTC, absidue commented
@efb4f5ff-1298-471a-8973-3d47447115dc Commited it to this pull request, please review it again.

2022-05-22 15:01 UTC, ChunkyProgrammer submitted a review, later dismissed

2022-05-22 15:10 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Checked out all the languages just to be sure

Retrieves language based on IP if u switch to the following languages

- Norsk nynorsk
- system default

2022-05-22 15:18 UTC, absidue commented
That's because the closest YouTube has is "Norsk" which is `no`, however FreeTube has "Norsk nynorsk" (`nn`) and "Norsk bokmål" (`nb_NO`) so YouTube has no idea what `nn` is. I don't know how different "Norsk" and "Norsk nynorsk" are, if they are close enough I can add a special case to the code which sends `no` to YouTube if the language is set to `nn`.

2022-05-22 15:34 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> That's because the closest YouTube has is "Norsk" which is `no`, however FreeTube has "Norsk nynorsk" (`nn`) and "Norsk bokmål" (`nb_NO`) so YouTube has no idea what `nn` is. I don't know how different "Norsk" and "Norsk nynorsk" are, if they are close enough I can add a special case to the code which sends `no` to YouTube if the language is set to `nn`.

Quick search on the web leads me to believe that it is the same

2022-05-22 16:25 UTC, absidue commented
Added special handling for Norsk nynorsk.

2022-05-22 16:40 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> Checked out all the languages just to be sure
> 
> Retrieves language based on IP if u switch to the following languages
> 
>     * Norsk nynorsk
> 
>     * system default

So if my IP is from Germany but the default language is English on my system. It will show me a German format instead of the System language. Which is understandable because YT doesnt have a langaguage thats called ```system default```

2022-05-22 16:59 UTC, absidue commented
FreeTube doesn't actually use the system language it picks the closest one to your system language and defaults to `en-US` if it doesn't have localisations for your system language ([`src/renderer/store/modules/settings.js` lines 232-245](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/store/modules/settings.js#L232-L245)). Maybe YouTube doesn't accept `en-US` as a valid language. If it doesn't like it then there are probably also a bunch of others it doesn't like, in which case I will need to add a list of which YouTube language should be used for each FreeTube language.

As I don't have access to your computer and your specific setup you might want to test it by adding `console.log(locale)` to [`src/renderer/store/modules/ytdl.js` line 296](https://github.com/absidue/FreeTube/blob/048379587d8464d88ec9aab464a5d7df87c20109/src/renderer/store/modules/ytdl.js#L296) and check what it logs in the devtools console for you.

2022-05-23 01:35 UTC, PikachuEXE approved these changes
Tested with Traditional Chinese

Should I test Norsk nynorsk too?

Playlist for testing:
- https://youtube.com/playlist?list=PLTariUrSxayszFKmTdIyty9MI28gFILvb

2022-05-23 15:12 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> Should I test Norsk nynorsk too?

@PikachuEXE just tested it and it works

2022-05-27 02:49 UTC, ChunkyProgrammer approved these changes
This issue with system happens elsewhere in the code so i am okay with approving the PR as is and having another PR fix the locales here & elsewhere

2022-05-29 23:14 UTC, ChunkyProgrammer commented
Maybe include 
`import i18n from '../../i18n/index'
`
at the top
and then get the current locale with:
`i18n.locale`

2022-05-29 23:15 UTC, ChunkyProgrammer requested changes

2022-05-29 23:15 UTC, ChunkyProgrammer commented on src/renderer/store/modules/ytdl.js
> +      let locale = settings.currentLocale.replace('_', '-')
Maybe include
import i18n from '../../i18n/index'
at the top
and then get the current locale with:
i18n.locale

2022-05-29 23:15 UTC, ChunkyProgrammer commented on src/renderer/views/Playlist/Playlist.js
> +      return this.$store.getters.getCurrentLocale.replace('_', '-')
Maybe include
import i18n from '../../i18n/index'
at the top
and then get the current locale with:
i18n.locale

2022-05-30 15:46 UTC, absidue commented
I've updated the PR with @ChunkyProgrammer's requested changes

2022-05-30 21:54 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
LGTM!

2022-05-31 01:38 UTC, PikachuEXE approved these changes

2022-05-31 01:43 UTC, ChunkyProgrammer approved these changes

2022-05-31 01:43 UTC, merged