Playlist page improvements
FreeTubeApp/FreeTube pull request #2281
Opened 2022-05-31 16:59 UTC by vallode

---
Playlist page improvements
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
Closes #2255

**Description**
Small love and care to the playlist templates:

* Add thumbnail hover visual on videos
* Fixes issue with overflow not being visible on the playlist description
* Fixes issue where playlist description whitespaces would not be rendered
* Changes the channel icon to be a bit smaller to save space
* Changes a few styles to the playlist stats

**Screenshots (if appropriate)**
Please add before and after screenshots if there is a visible change.

Before:
![image](https://user-images.githubusercontent.com/18506096/171231357-e4b65532-6a68-4827-8800-078a5d4c0854.png)

After:
![image](https://user-images.githubusercontent.com/18506096/171231292-20657673-61d0-42fe-8271-ddef10556db3.png)

**Testing (for code that is not small enough to be easily understandable)**
Just played around with playlists and smaller views.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10
 - OS Version: [e.g. 22] Debian
 - FreeTube version: [e.g. 0.8] upstream/development

2022-05-31 20:00 UTC, absidue requested changes
Please fix the missing new lines and the share menu getting cut off.

Playlist in the screenshots: https://www.youtube.com/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU

Share menu in development:
![development-share](https://user-images.githubusercontent.com/48293849/171274227-7addf34e-9727-4509-af1e-b1abb5112cbe.jpg)

Normal with this PR:
![this-pr-normal](https://user-images.githubusercontent.com/48293849/171274299-919bd68b-0d75-4d5e-a4c2-460bca775664.jpg)

Hovering over the share menu with this PR:
![this-pr-share](https://user-images.githubusercontent.com/48293849/171274389-3ae13050-3057-4eb1-85a1-646e4b81edb2.jpg)

2022-06-02 22:36 UTC, absidue submitted a review, later dismissed
Looks good now. Thanks.

2022-06-03 13:20 UTC, ChunkyProgrammer commented on src/renderer/components/playlist-info/playlist-info.vue
> +    ></p>
lint issue
```suggestion
    >
```

2022-06-04 06:38 UTC, PikachuEXE approved these changes

2022-06-04 21:51 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
LGTM!

2022-06-04 21:51 UTC, merged