Fix the redundant navigation error
FreeTubeApp/FreeTube pull request #2286
Opened 2022-06-01 21:40 UTC by absidue

---
Fix the redundant navigation error
---

**Pull Request Type**

- [x] Bugfix

**Description**

Fixes the issue where spamming the nav buttons throws vue errors about redundant navigations.

**Screenshots (if appropriate)**
![duplicate-navigation-error](https://user-images.githubusercontent.com/48293849/171503845-d142e9ec-1946-49a8-8305-b5c34a0bd761.jpg)

**Testing (for code that is not small enough to be easily understandable)**
I spammed the nav buttons and the error didn't occur anymore.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: 7287e0011ee21cb6d827c979b4cff2a44bc2ee6b

**Additional context**
Add any other context about the problem here.

2022-06-01 22:53 UTC, ChunkyProgrammer commented
Error still appears when clicking the profile setting icon
![image](https://user-images.githubusercontent.com/78101139/171514504-d6ba9fc7-a7d1-49c9-971a-f3f0f0455e17.png)

2022-06-03 02:50 UTC, ChunkyProgrammer commented
Was able to have this error happen again when searching (search the same thing twice)

2022-06-05 08:53 UTC, vallode commented
Potentially we need to hijack the prototype of the vue-router push function here? I mean is it feasible to expect every single next router interaction to always remember to put this if statement in place?

2022-06-05 09:12 UTC, absidue commented
I thought about that but I haven't looked into the source code for that yet (if you want to take a look remember to look at the source code for the version that FreeTube uses). Although I'll need to expand the checks to also check the query parameters etc.

2022-06-09 17:01 UTC, absidue commented
I've now removed the individual checks and wrapped the router push function in one that checks the path and query before navigating.

2022-06-10 02:27 UTC, PikachuEXE commented
Can we have a summary of what to be tested?

2022-06-11 03:37 UTC, PikachuEXE reviewed
Tested
- spamming the nav buttons
- clicking the profile select's setting icon
- search the same thing twice
- Paste a YT Video URL to navbar, press arrow button multiple times

2022-06-11 03:45 UTC, PikachuEXE requested changes
Cleanup duplicate statements (especially conditional)

`isQueryEmpty` can also be removed

2022-06-11 03:45 UTC, PikachuEXE commented on src/renderer/router/index.js
> +    }
```suggestion
    const currentQueryUSP = new URLSearchParams(router.currentRoute.query)
    let newPath = ''
    let newQueryUSP = new URLSearchParams()

    if (typeof location === 'string') {
      if (location.includes('?')) {
        const urlParts = location.split('?')
        newPath = urlParts[0]
        newQueryUSP = new URLSearchParams(urlParts[1])
      } else {
        newPath = location
        // newQueryUSP already empty
      }
    } else {
      newPath = location.path
      newQueryUSP = new URLSearchParams(location.query)
    }

    const pathsAreDiff = router.currentRoute.path !== newPath
    // Comparing `URLSearchParams` objects directly will always be different
    const queriesAreDiff = newQueryUSP.toString() !== currentQueryUSP.toString()

    if (pathsAreDiff || queriesAreDiff) {
      return super.push(location)
    }
```

2022-06-12 01:34 UTC, PikachuEXE approved these changes

2022-06-12 01:36 UTC, PikachuEXE commented on src/renderer/router/index.js
> +    }
Irrelevant now but I think
```js
location.path !== router.currentRoute.path &&
        (isQueryEmpty(location.query) ||
          location.query !== router.currentRoute.query)
```
is a wrong conditional statement
Upper conditional statements are like (new path != cur path **or** new query != cur query) (I think)
This one is (new path != cur path **and** new query != cur query) ?

2022-06-19 21:34 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
LGTM

2022-06-20 15:01 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@ChunkyProgrammer sorry for the spam :D

2022-06-21 02:29 UTC, merged