Fix ft-input bug padding
FreeTubeApp/FreeTube pull request #2287
Opened 2022-06-02 15:56 UTC by vallode

---
Fix ft-input bug padding
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
#2279

**Description**
Fixes bug found by @PikachuEXE https://github.com/FreeTubeApp/FreeTube/pull/2279#issuecomment-1144835903
I made the padding trick only happen on the main search input, this should fix it for the rest of the inputs across the app.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10
 - OS Version: [e.g. 22] Debian
 - FreeTube version: [e.g. 0.8] upstream/development

**Additional context**
Thanks for catching it pika

2022-06-03 12:10 UTC, PikachuEXE requested changes
Expected
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/1018543/171850882-c1548f91-1e50-4527-ba6c-b1d66df7459c.png">

Actual
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/1018543/171850962-da06f878-ab4c-4245-a8e7-698f20ce3c0f.png">

2022-06-04 08:34 UTC, PikachuEXE approved these changes
Tested locally

2022-06-04 21:06 UTC, absidue approved these changes

2022-06-04 21:38 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-06-04 21:38 UTC, merged