Add paste and go to context menu
FreeTubeApp/FreeTube pull request #2294
Opened 2022-06-05 20:57 UTC by vallode

---
Add paste and go to context menu
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Feature Implementation

**Related issue**
Closes #2273

**Description**
Adds "paste and go" to context menu

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10
 - OS Version: [e.g. 22] Debian
 - FreeTube version: [e.g. 0.8] upstream/development

2022-06-05 22:06 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
https://user-images.githubusercontent.com/73130443/172072609-e4106b2e-c260-45d0-a925-3128d190e842.mp4

2022-06-06 09:25 UTC, vallode commented
@efb4f5ff-1298-471a-8973-3d47447115dc can't replicate :/ I'm not even sure why this would happen, I only changed the label in line with the discussion in #2277

2022-06-08 11:42 UTC, vallode commented
@ChunkyProgrammer @absidue if you have time could you test this out? Not sure why the above issue would happen with this PR.

2022-06-10 01:36 UTC, PikachuEXE commented
@efb4f5ff-1298-471a-8973-3d47447115dc 
I have no problem

https://user-images.githubusercontent.com/1018543/172972677-40494489-8397-4de3-8154-56295129862a.mov

2022-06-10 01:41 UTC, PikachuEXE reviewed
I tested on search input on navbar and history/playlist tab

However I am unsure whether it should appear in input boxes in settings (and other places that's not for searching)

![Screenshot 2022-06-10 at 09 38 01](https://user-images.githubusercontent.com/1018543/172972997-4213e9c5-d0b3-45d1-a07a-6830ad4c8412.png)
![Screenshot 2022-06-10 at 09 38 21](https://user-images.githubusercontent.com/1018543/172973006-739fc1b4-5a56-4d2d-a807-653ea3dd9f4d.png)
![Screenshot 2022-06-10 at 09 38 28](https://user-images.githubusercontent.com/1018543/172973009-3c3584d9-cfbf-4f82-aa12-3522d1f9719f.png)

2022-06-10 01:41 UTC, PikachuEXE reviewed
I tested on search input on navbar and history/playlist tab

However I am unsure whether it should appear in input boxes in settings (and other places that's not for searching)

![Screenshot 2022-06-10 at 09 38 01](https://user-images.githubusercontent.com/1018543/172972997-4213e9c5-d0b3-45d1-a07a-6830ad4c8412.png)
![Screenshot 2022-06-10 at 09 38 21](https://user-images.githubusercontent.com/1018543/172973006-739fc1b4-5a56-4d2d-a807-653ea3dd9f4d.png)
![Screenshot 2022-06-10 at 09 38 28](https://user-images.githubusercontent.com/1018543/172973009-3c3584d9-cfbf-4f82-aa12-3522d1f9719f.png)

2022-06-19 20:06 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes

2022-06-19 20:06 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on src/main/index.js
> +        label: 'Toggle Video Statistics',
change to [Show / Hide Video Statistics](https://github.com/FreeTubeApp/FreeTube/issues/2277#issuecomment-1146831705)

2022-07-08 08:37 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
I agree with @PikachuEXE it should be removed on pages where it is unnecessary to use this

like the history, playlist and settings page

but also here
![Screenshot (257)](https://user-images.githubusercontent.com/73130443/177952216-53e10ba6-a584-4090-8718-a40b4f3da124.png)

2022-09-01 16:05 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@vallode please implement the requested changes

2022-10-17 14:25 UTC, absidue commented
I don't think this is possible to implement unless stuff changes on Electron's side and they start passing the id or the classes of the element along with the context menu event. Currently there is no way to check if a specific search box was right clicked on.

2022-11-30 02:02 UTC, closed without merging