Fix blog banner layout
FreeTubeApp/FreeTube pull request #2300
Opened 2022-06-08 11:57 UTC by vallode

---
Title
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
Closes #2297

**Description**
Fixes a layout error with the blog notification banner

**Screenshots (if appropriate)**
After:
![image](https://user-images.githubusercontent.com/18506096/172610657-3f92a48a-56a6-4f7b-8a0f-532cebcb06b4.png)

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - OS Version: [e.g. 22]
 - FreeTube version: [e.g. 0.8]

**Additional context**
Add any other context about the problem here.

2022-06-10 09:56 UTC, vallode commented on src/renderer/App.vue
> -      v-if="showUpdatesBanner || showBlogBanner"
I nested the routerview within this and the v-ifs were already on the individual elements anyway, this statement is unnecessary now.

2022-06-19 19:50 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
could u also create a PR in the RC branch?

2022-07-04 08:10 UTC, PikachuEXE approved these changes
Local test result:

Before fix
![image](https://user-images.githubusercontent.com/1018543/177111276-d9aaf6ea-a67a-43dd-8f42-e25c4e5cca58.png)

After fix
![image](https://user-images.githubusercontent.com/1018543/177111375-99c607d0-3a32-47e3-a92f-64ebd7fb54de.png)

2022-07-04 08:42 UTC, absidue commented
This PR unfortunately doesn't fix the issue entirely on my end.

**New version banner**
Testing:
1. change version in package.json to `0.15.0`
2. `yarn run dev`

Result:
![new_version_banner](https://user-images.githubusercontent.com/48293849/177116759-dc8f3dab-d407-4ffe-8bf2-7fc4a5098809.png)

**New blog banner**
Testing:
1. `yarn run dev`
2. In the devtools: Application -> Local Storage -> `http://localhost:9080`
3. Delete `lastAppWasRunning` key
4. Close FreeTube
5. `yarn run dev`

Result:
![new_blog_banner](https://user-images.githubusercontent.com/48293849/177117269-31100a01-a8e9-407e-91ed-2411b74075f6.png)

2022-07-04 09:00 UTC, absidue requested changes
Looks like the banner is greedy and tries to take up as much space as possible.

Loading screen while searching:
![loading_screen](https://user-images.githubusercontent.com/48293849/177120719-a1281583-39a0-4757-a354-473756e5d982.png)

Search results:
![search_results](https://user-images.githubusercontent.com/48293849/177120858-d118b9f2-bd12-4183-ab6c-47a806b57614.jpg)

2022-07-05 05:39 UTC, PikachuEXE commented
@vallode 
I tried to fix it and here is my maybe WIP result
https://github.com/FreeTubeApp/FreeTube/compare/development...PikachuEXE:FreeTube:fix-blog-notification-pika

https://user-images.githubusercontent.com/1018543/177257127-0eb4a1f9-dcd5-486d-93fd-3336b3ff6c76.mov

2022-07-05 05:45 UTC, PikachuEXE commented
You can experiment with more properties with
https://the-echoplex.net/flexyboxes/?fixed-height=on&display=flex&flex-direction=column&flex-wrap=nowrap&justify-content=flex-start&align-items=center&align-content=stretch&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=1&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto

2022-07-05 10:57 UTC, vallode commented
Thanks everyone for the reminders, been going through some personal stuff. Fixed it for now, should I open a new PR for the release candidate too?

2022-07-05 11:34 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
>  should I open a new PR for the release candidate too?

@vallode yes please! :)

2022-07-06 08:11 UTC, absidue approved these changes
Thank you, looks good now

2022-07-07 17:43 UTC, GilgusMaximus approved these changes
Tested locally, works well. No problems at different sizes or with different amount of videos

2022-07-07 17:43 UTC, merged