Clear filter when clicked "Clear input" [0.17RC]
FreeTubeApp/FreeTube pull request #2348
Opened 2022-06-21 10:27 UTC by hockerschwan

**Pull Request Type**
- [x] Bugfix

**Related issue**
#2346

**Description**
>1. Add items to userplaylists and history
>2. Filter to show fewer results
>3. Click "Clear input"
>4. Filter state persists, not showing all items

**Screenshots (if appropriate)**
Before
<video src="https://user-images.githubusercontent.com/80553357/174777700-f4107b9b-5a10-4425-bfae-4894a27a4ac7.mp4">

After
<video src="https://user-images.githubusercontent.com/80553357/174777514-28d4f9ef-6caf-460c-951e-6f6efd26cec8.mp4">

**Desktop (please complete the following information):**
 - OS: Windows10 21H1
 - FreeTube version: d1a7bc301103f3680ae06882449703d7828c0fed

2022-06-21 11:19 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-06-21 21:05 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Hi @hockerschwan i didnt actually test this but could it be that https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-2934372 the last one on the list is related?

2022-06-22 08:38 UTC, absidue requested changes
Please create a separate branch for this pull request, that is based on the RC branch, currently you are pulling in all the changes from the dev branch into the RC branch

2022-06-22 16:11 UTC, closed without merging

2022-06-22 16:51 UTC, hockerschwan commented
oops. new one is #2350
<br>
>could it be that https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-2934372 the last one on the list is related?

no it's related to
https://github.com/FreeTubeApp/FreeTube/blob/e0b682b771f0b3627c6adf27b42df21fddae6161/src/renderer/components/ft-input/ft-input.js#L202-L206
 it should be `this.visibleDataList.length`