fix: search suggestion get stuck [rc]
FreeTubeApp/FreeTube pull request #2354
Opened 2022-06-22 17:48 UTC by hockerschwan

Please select what type of pull request this is:
- [x] Bugfix

**Related issue**
https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-2934372

**Description**
>search something -> see search suggestions -> navigate through the suggestions with the arrow keys on your key board -> get stuck

**Screenshots (if appropriate)**
<video src="https://user-images.githubusercontent.com/80553357/175103121-5d055ead-8abb-4e93-ad7b-4b1ddc64a985.mp4">

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - FreeTube version: 0.17rc

2022-06-23 19:14 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
still got stuck in this version though?

2022-06-30 18:16 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
Just noticed that i mixed up PRs. This works!

2022-06-30 21:17 UTC, absidue approved these changes

2022-07-01 08:30 UTC, PikachuEXE approved these changes

2022-07-01 08:30 UTC, merged