Added warning to external player tooltip
FreeTubeApp/FreeTube pull request #2387
Opened 2022-07-08 09:02 UTC by efb4f5ff-1298-471a-8973-3d47447115dc

---
Added warning to external player tooltip
---

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [x] Feature Implementation

**Related issue**
https://github.com/FreeTubeApp/FreeTube/issues/2373

**Description**
Add a warning to the already existing tooltip message.

**Testing (for code that is not small enough to be easily understandable)**
I checked if the text has changed

**Desktop (please complete the following information):**
 - OS: win10
 - OS Version: 21h2
 - FreeTube version: bleeding edge

2022-07-08 09:03 UTC, absidue requested changes

2022-07-08 09:03 UTC, absidue commented on static/locales/en-US.yaml
> +      video (playlist if supported) in the external player, on the thumbnail. Warning, Invidious settings does not affect external players.
```suggestion
      video (playlist if supported) in the external player, on the thumbnail. Warning, Invidious settings do not affect external players.
```

2022-07-08 09:06 UTC, absidue approved these changes
Looks good to me, thanks.

2022-07-08 09:08 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> Looks good to me, thanks.

@absidue tested this in my ubuntu vm (always double check my pr's in there) and i didnt see the message change :(

2022-07-08 09:10 UTC, absidue commented
@efb4f5ff-1298-471a-8973-3d47447115dc did you explicitly set the language in the FreeTube settings to en-US?

2022-07-08 09:11 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> @efb4f5ff-1298-471a-8973-3d47447115dc did you explicitly set the language in the FreeTube settings to en-US?

yeah nvm i just wanted to comment that im stupid 😅

2022-07-08 09:12 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
i had it set to `system default` and assumed it was the same as en-US

2022-07-08 10:04 UTC, PikachuEXE approved these changes

2022-07-09 15:26 UTC, Svallinn approved these changes

2022-07-09 15:26 UTC, merged