Fix for banner and too far scrolling
FreeTubeApp/FreeTube pull request #2399
Opened 2022-07-12 21:33 UTC by GilgusMaximus

---
Fix for banner and too far scrolling
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
From dev channel

**Description**
The last fix for the overflowing banner introduced a bug that lets you scroll past the video section on any page.
This is now fixed by a small restructuring of how the app layout works and how it is styled

**Testing (for code that is not small enough to be easily understandable)**
Tested with and without banner

**Desktop (please complete the following information):**
 - OS: Win
 - OS Version: 10
 - FreeTube version: v0.17.0-RC

2022-07-13 01:48 UTC, PikachuEXE requested changes
https://github.com/FreeTubeApp/FreeTube/pull/2398#discussion_r919560736

2022-07-13 16:11 UTC, GilgusMaximus commented
Updated the last line

2022-07-14 01:35 UTC, PikachuEXE approved these changes

2022-07-14 14:16 UTC, ChunkyProgrammer approved these changes
Lgtm

2022-07-16 09:30 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-07-16 09:30 UTC, merged