Update README.md
FreeTubeApp/FreeTube pull request #2437
Opened 2022-08-01 13:50 UTC by PeterDaveHello

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [ ] Feature Implementation
- [x] Documentation

**Description**

Add link of LibRedirect and remove the download links of Privacy Redirect.

The development of Privacy Redirect looks pending for a while, the forked LibRedirect seems to be its successor with more active maintenance, should be worthy to be mentioned here.

2022-08-02 00:16 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Dont change the order

Prvacyresirecr first
Libredirect second

2022-08-02 00:16 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
See previous comment

2022-08-02 17:38 UTC, PeterDaveHello commented
Updated.

2022-08-02 17:42 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes

2022-08-02 17:42 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on README.md
> +Download Privacy Redirect for [Firefox](https://addons.mozilla.org/firefox/addon/libredirect/) or [Google Chrome](https://github.com/libredirect/libredirect/blob/master/chromium.md).
It should say Download LibRedirect

The chrome link is not an url from the chrome store

2022-08-02 21:03 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-08-04 20:29 UTC, ChunkyProgrammer approved these changes

2022-08-04 20:50 UTC, absidue approved these changes

2022-08-04 20:50 UTC, merged