Update ft-icon-button.sass
FreeTubeApp/FreeTube pull request #2648
Opened 2022-09-30 20:23 UTC by rolandoangulo

# Title

## Pull Request Type

- [ ] Bugfix
- [X] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

closes #1746

## Description

Only show the favorite icon on hover
## Screenshots 

## Testing 

## Desktop

- **OS:**
- **OS Version:**
- **FreeTube version:**

## Additional context

2022-09-30 21:03 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Hi there, i understand that this is an easy to understand PR but please do fill out the template!

2022-09-30 23:49 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
This does only work when u hover in the top right corner of the thumbnail. I think its better to show when u hover over any position of the thumbnail

2022-10-01 05:54 UTC, absidue requested changes
Instead of changing the ft-icon-button component, in a way that will break every other use of the ft-icon-button component in FreeTube, please make the changes to only the component that has the favourites button. You should not have to make any changes to the ft-icon-button component files to implement this feature.

2022-10-01 11:03 UTC, absidue commented
Sorry my comment earlier was a bit harsh. I recommend looking at the `ft-list-video` component instead of the `ft-icon-button` component, that way your changes will only affect the favourites button as well as being able to fix the issue that @efb4f5ff-1298-471a-8973-3d47447115dc noticed while testing.

P.S. you should be able to make it show and hide the favourites button when the thumbnail wrapper is being hovered over, purely in CSS without needing much code for it.

2022-11-19 02:08 UTC, closed without merging