Fix the trending and watch pages swallowing the arrow key events
FreeTubeApp/FreeTube pull request #3170
Opened 2023-02-07 22:00 UTC by absidue

#  Fix the trending and watch pages swallowing the arrow key events

## Pull Request Type

- [x] Bugfix

## Related issue
closes #3160

## Description
Currently the trending and watch pages swallow the arrow key events, even when you use the alt+arrow key shortcuts.

## Testing 
Focus the different trending tabs with the left and right arrow keys and also try navigating back and forward with alt+arrow key

## Desktop

- **OS:** Windows
- **OS Version:** 10
- **FreeTube version:** 0.18.0

2023-02-07 23:48 UTC, ChunkyProgrammer submitted a review, later dismissed

2023-02-08 01:50 UTC, PikachuEXE approved these changes
![image](https://user-images.githubusercontent.com/1018543/217408048-a4983ea0-de99-445b-8f35-d1095e478847.png)

2023-02-08 18:49 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
Video page still swallows the arrow keys :(

2023-02-08 18:54 UTC, ChunkyProgrammer commented
> Video page still swallows the arrow keys :(

I think this or is just for fixing the trending page

2023-02-08 19:01 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> > Video page still swallows the arrow keys :(
> 
> I think this or is just for fixing the trending page

Ah if that is the case i can approve it but this pr doesnt fully close the issue.

2023-02-09 18:19 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
lgtm

2023-02-10 03:51 UTC, PikachuEXE approved these changes
Tested video watch view

2023-02-10 17:44 UTC, ChunkyProgrammer approved these changes

2023-02-10 17:44 UTC, merged