IV: Fix search cache issues when fetching more
FreeTubeApp/FreeTube pull request #3486
Opened 2023-05-03 20:13 UTC by ChunkyProgrammer

# IV: Fix search cache issues when fetching more

## Pull Request Type
- [x] Bugfix

## Related issue
closes https://github.com/FreeTubeApp/FreeTube/issues/1900

## Description
- save next page data for fetch more in cache
- add apiUsed to cache

## Testing 
See: https://github.com/FreeTubeApp/FreeTube/issues/1900#issuecomment-1128816160

## Desktop
- **OS:** Windows
- **OS Version:** 11
- **FreeTube version:** 0.18.0

2023-05-04 01:28 UTC, PikachuEXE requested changes
Tested https://github.com/FreeTubeApp/FreeTube/issues/1900#issuecomment-1128816160

2023-05-04 01:28 UTC, PikachuEXE commented on src/renderer/store/modules/utils.js
> +      }
```suggestion
      if (payload.nextPageRef) {
        // Local API
        state.sessionSearchHistory[sameSearch].nextPageRef = payload.nextPageRef
      } else if (payload.searchPage) {
        // Invidious API
        state.sessionSearchHistory[sameSearch].searchPage = payload.searchPage
      }
```

2023-05-05 21:12 UTC, absidue commented
Erm so weird thing happens with these steps on the local API:
1. Search for something
2. Click load more
3. Navigate back to the previous page
4. Navigate forward again
5. Click load more

loading icon shows up and you only have one page of results, even though there should be 3

2023-05-06 08:58 UTC, PikachuEXE commented
I think #1900 is not about Local API?
Not saying we shouldn't fix it but not sure how easy to fix the Local API issue
If easy enough let's fix it in this PR 
If not let's merge this PR first and create a separate issue (or draft PR)

2023-05-06 18:24 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> I think #1900 is not about Local API? Not saying we shouldn't fix it but not sure how easy to fix the Local API issue If easy enough let's fix it in this PR If not let's merge this PR first and create a separate issue (or draft PR)

it isnt about the local api? maybe see https://github.com/FreeTubeApp/FreeTube/issues/1900#issuecomment-1129087659 to understand the issue better?

2023-05-06 18:24 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
works, lgtm

2023-05-06 18:29 UTC, ChunkyProgrammer commented
Absidue is mentioning a regression from this PR. I believe I fixed it here: https://github.com/FreeTubeApp/FreeTube/pull/3486/commits/63ed793130a525353749157bc487c52ab6f35203

🙂

2023-05-07 07:18 UTC, PikachuEXE approved these changes

2023-05-13 11:18 UTC, absidue approved these changes

2023-05-13 11:18 UTC, merged