Show chapter title on seek bar
FreeTubeApp/FreeTube pull request #3977
Opened 2023-08-30 10:55 UTC by Benjababe

# Show Chapter Title on Seek Bar

## Pull Request Type

- [x] Feature Implementation

## Related issue

Closes #2829 

## Description
Includes the current chapter hovered with the time in the seeker info, only affects videos with chapters.
Jitters sometimes when the chapter tooltip exceeds the player as it's being moved back into the player's boundaries

## Screenshots 

[Before](https://github.com/FreeTubeApp/FreeTube/assets/19561469/a65f5cc0-11dd-43e6-bdee-a3d58a618ef5)
[After](https://github.com/FreeTubeApp/FreeTube/assets/19561469/d803457c-ff6e-4e2f-8101-eabcf8fde751)

## Testing 
Tried on [this](https://www.youtube.com/watch?v=Q9ejVtGh2Vw) and [this](https://www.youtube.com/watch?v=0cTpTMl8kFY), seemed fine.

## Desktop

- **OS:** Windows 10
- **OS Version:** 22H2
- **FreeTube version:**

2023-08-30 11:16 UTC, PikachuEXE requested changes
1. Missing final new line (already set in `.editorconfig`)
2. There are a lot of changes in `src/renderer/videoJS.css` but many changes are formatting changes. Possible to revert those for easier review?

2023-08-30 11:22 UTC, absidue commented
I agree with pikachu please revert all the unrelated formatting changes. I don't know if you have your editor set to automatically format the files or something, but unrelated formatting changes seem to be a common pattern across all of your pull requests.

2023-08-30 19:42 UTC, Benjababe commented
> Comparing the first and second video, it looks like the progress bar no longer stretches the full width of the player.

Thanks for spotting it, I had made a small mistake with the styling

2023-09-06 14:25 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
LGTM

2023-09-06 14:43 UTC, absidue commented
I'm really not looking forward to trying to port this to shaka (will probably require even more code there, as you'll have to fight against the javascript that scales and positions their built-in thumbnail display, every time the mouse moves) :(

2023-09-06 15:10 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Should this wait until we've migrated?

2023-09-06 16:05 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
> would you prefer to not have it at all, until someone creates a pull request to add it to shaka, after we've got the shaka stuff merged in?

I prefer this tbh

2023-09-07 01:14 UTC, PikachuEXE commented on src/renderer/components/ft-video-player/ft-video-player.js
> +          }
Too long
```suggestion
          if (!thumbnail) { return }
```

2023-09-07 01:18 UTC, PikachuEXE requested changes

2023-09-07 01:18 UTC, PikachuEXE commented on src/renderer/components/ft-video-player/ft-video-player.js
> +        }
Unnecessary nesting IMO
```suggestion
        if (noMarkerHovered) {
          sponsorBlockTooltip.style.visibility = 'hidden'
          return
        }
        
        const { left: mouseDisplayLeft } = mouseDisplay.getBoundingClientRect()
        const { left: playerLeft, right: playerRight } = this.player.el().getBoundingClientRect()
        const { width: sbTooltipWidth } = sponsorBlockTooltip.getBoundingClientRect()

        let calculatedRight = -(sbTooltipWidth / 2)

        // Gets left and right boundaries of the chapter tooltip
        // +1 for rightX to include width of the mouse display
        const sbTooltipLeftX = mouseDisplayLeft - (sbTooltipWidth / 2)
        const sbTooltipRightX = mouseDisplayLeft + 1 + (sbTooltipWidth / 2)

        // If tooltip extends outside of the video player
        // Adjust CSS right property to fit the tooltip within the player
        if (sbTooltipLeftX < playerLeft) {
          calculatedRight -= (playerLeft - sbTooltipLeftX)
        } else if (sbTooltipRightX > playerRight) {
          calculatedRight += (sbTooltipRightX - playerRight)
        }

        sponsorBlockTooltip.style.right = `${calculatedRight}px`
```

2023-09-07 01:18 UTC, PikachuEXE commented on src/renderer/components/ft-video-player/ft-video-player.js
> +          }
I am not sure if the blank line should be kept, up to you
```suggestion
          if (visibleChildren.length === 0) { return }
```

2023-09-11 11:48 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@absidue do you recommend putting this on hold?

2023-10-12 08:36 UTC, absidue commented
Yes, especially as I see no way of implementing this with shaka-player, without modifying shaka-player itself. Without modifying shaka-player, you will be in a constant battle against it's JavaScript, because the entire thumbnail display is managed through JavaScript, even the positioning, so that is usable without their CSS (to allow people to use custom themes for the player).

2024-04-03 13:43 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Will revisit this one after the migration.

2024-04-03 13:43 UTC, closed without merging