Highlights comments. #783
FreeTubeApp/FreeTube pull request #4272
Opened 2023-11-02 19:23 UTC by ab-shrek

# Title
Highlights comments.

## Pull Request Type

- [ ] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

Fixes #783

## Description

Adds functionality to highlight or unhighlight a comment or a comment reply.
If the comment or reply timestamp is clicked, the highlight gets toggled to on or off.
The highlighted comments move to the top and on unhighlight, they move back to the original position
The highlighted replies move to the top and on unhighlight, they stay at the same position. The associated comment moves to the top if reply gets highlighted and back to original position once none of the replies are highlighted anymore.

## Screenshots 

## Testing 

Tested manually.

## Desktop

- **OS:**
- **OS Version:**
- **FreeTube version:**

## Additional context

2023-11-02 20:43 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Please provide some testcases in the testing section of the PR body

Think of testcases u used while testing this PR

2023-11-12 23:52 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed
LGTM

2023-11-13 01:37 UTC, PikachuEXE commented
### Comment level

#### 1st page
A1. Click unhighlighted to highlight + move to top = OK
A2. Reload page & highlighted stay on top = OK
A3. Click highlighted to unhighlight + move back = OK

#### 2nd (or later) pages
A4. Click unhighlighted to highlight + move position = OK (present on top even 2nd+ page not loaded)
A5. Reload page & highlighted stay on top = OK
A6. Click highlighted to unhighlight + move back = OK (I guess it can only fall into bottom of 1st page when 2nd+ page not loaded)

### Reply level

#### 1st page
B1. Click unhighlighted to highlight + move position = OK
B2. Reload page & highlighted stay on top = NOT OK (stay in original position)
B3. Click highlighted to unhighlight + stay position = OK

#### 2nd (or later) pages
B4. Click unhighlighted to highlight + move position = OK
B5. Reload page & highlighted stay on top = NOT OK (or is this intended? Anyway it's different from comments)
B6. Click highlighted to unhighlight + stay position = OK

B2. 
![image](https://github.com/FreeTubeApp/FreeTube/assets/1018543/91802931-f7d6-46d7-bd56-cb30e61220c5)

2023-11-13 16:23 UTC, ab-shrek commented
@PikachuEXE the latest changes take care of the highlighted replies not showing up on top on a reload. I did a commit --amend on the earlier commit. Can you review the changes now; please? Thanks

2023-11-14 00:44 UTC, PikachuEXE commented
Please try to avoid `commit --amend` next time since it makes checkout later diff slightly more difficult
Coz I (and maybe others) use `gh pr checkout 4272` from the code button and it won't checkout if remote commits are amended
![image](https://github.com/FreeTubeApp/FreeTube/assets/1018543/8fb6e718-bf65-439c-b86d-388ac2dab381)

(You are still free to do that before submitting PR to make commit history look better which I also do, but avoid it after PR opened)

2023-11-14 00:48 UTC, PikachuEXE commented
Re-tested B2 & B5 and they are now OK

2023-11-14 00:52 UTC, PikachuEXE approved these changes

2023-11-14 00:53 UTC, PikachuEXE requested changes
Crap, wrong button

2023-11-14 00:53 UTC, PikachuEXE commented on src/renderer/components/watch-video-comments/watch-video-comments.vue
> +              {{ $t("Highlighted reply") }}
Refer to all new code with new translation entry:
- Missing new entries in `static/locales/en-US.yaml`
- The key probably should be under `Comments` like `Comments.Pinned by` in the same file

2023-11-14 03:54 UTC, ab-shrek commented
@PikachuEXE thanks for the effort. I did a git commit for the requested change this time :)

2023-11-14 07:00 UTC, PikachuEXE approved these changes

2023-11-14 08:08 UTC, absidue commented
The code still needs a lot of changes before this can be approved, also the UX issues with having to click the timestamp instead of a dedicated button and having to reload the page.

Yes I know this pull request is based off a YouTube feature that has horrible UX, but just because YouTube thinks horrible UX is a good idea, doesn't mean that said horrible UX has to be copied over to FreeTube.

2023-11-14 08:59 UTC, absidue reviewed
Here are some of the code issues that need to be addressed. There are others like querying the store inside the template 5 times, for every comment, when you could just set a boolean property on the comment and reply saying that it is highlighted. That would perform so much better.

The two UX problems mentioned in the original pull request and my comment above should be addressed too.

2023-11-14 08:59 UTC, absidue commented on src/datastores/handlers/electron.js
Whenever you make changes to `src/datastores/handlers/electron.js`, you need to make the equivalent changes to `src/datastores/handlers/web.js` too.

2023-11-14 08:59 UTC, absidue commented on src/main/index.js
> +    console.error('mario index.js cases')
Don't leave test messages lying around. Also if you do add test messages, use `console.log`, that way the linter will complain about it before letting you commit, so you'll remember to remove it.

2023-11-14 08:59 UTC, absidue commented on src/renderer/components/watch-video-comments/watch-video-comments.css
> +}
Please make sure files end in a newline when you add new files and don't remove it from existing files.

2023-11-14 08:59 UTC, absidue commented on src/renderer/components/watch-video-comments/watch-video-comments.js
> +      return (comment) => this.isCommentHighlighted(comment) || this.getHighlightedReplies(comment.commentId).length > 0
Methods should be added to the `methods` section, not returned from computed properties. I'm guessing this is your first time coding with Vue, if yes you may want to read up on the options API, the official Vue 2 docs are a good place to start.

2023-11-14 08:59 UTC, absidue commented on src/renderer/components/watch-video-comments/watch-video-comments.js
> +        )
```suggestion
        parsedComments.forEach(comment => {
          comment.commentIndex = ++this.commentIndexCount
        })
```

2023-11-14 08:59 UTC, absidue commented on src/renderer/components/watch-video-comments/watch-video-comments.js
> +        }.bind(this))
```suggestion
        commentData.forEach((comment) => {
          comment.commentIndex = ++this.commentIndexCount
        })
```

2023-11-14 08:59 UTC, absidue commented on src/renderer/components/watch-video-comments/watch-video-comments.js
> +        await this.$store.dispatch('unhighlightComment', { videoId: this.id, comment: comment })
You already use `mapActions` at the bottom of the file, please use that for everything instead of doing some with that and others with `dispatch`.

2024-02-20 01:43 UTC, closed without merging