reset selected filters after search
FreeTubeApp/FreeTube pull request #5033
Opened 2024-04-28 09:17 UTC by ankitchauhan-aka

## Pull Request Type

- [ ] Bugfix
- [x] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue
closes #1693 

## Description

## Testing
1. Apply filters, You must have a red border that shows filter(s) are selected
2. Then search for a term in the search box and choose any option from autosuggestion dropdown
3. After selecting autosuggested options, Filters must be reset to default options.
4. The red border from the filter icon will be removed

2024-04-29 01:27 UTC, PikachuEXE requested changes
I tested with these steps and failed
- Enter something, enter search result via enter/search button
- Change filter options
- Press search button again
- Search result not updated but filter reset

![image](https://github.com/FreeTubeApp/FreeTube/assets/1018543/0ab3ec2e-0ea9-4d18-8f45-6887782b33fe)

2024-04-29 04:44 UTC, ankitchauhan-aka commented
> I tested with these steps and failed
> 
> * Enter something, enter search result via enter/search button
> * Change filter options
> * Press search button again
> * Search result not updated but filter reset
> 
> ![image](https://private-user-images.githubusercontent.com/1018543/326312157-0ab3ec2e-0ea9-4d18-8f45-6887782b33fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjYwMjMsIm5iZiI6MTcxNDM2NTcyMywicGF0aCI6Ii8xMDE4NTQzLzMyNjMxMjE1Ny0wYWIzZWMyZS0wZWE5LTRkMTgtOGY0NS02ODg3NzgyYjMzZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDQ0MjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI1MDExMTg2YTA1YzU3ZTczNThmMzZjMTdmZTdkZGNkZWMzZDZkNDAwZTliMmZmMjJlZDU3NTJmNzIwMTIwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7wvou9FDwnYVmpg_58bQN7h2wEhVazN8-prvt__i_wM)

@PikachuEXE I've just attached a test video with mentioned steps and not able to replicate issue. Could you please share similar so I can fix it asap.

2024-04-29 05:47 UTC, PikachuEXE commented
https://github.com/FreeTubeApp/FreeTube/assets/1018543/0f64ab14-8c03-4538-92a8-835ab0072b00

2024-04-29 17:52 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
Filter not applied when:

1. Application starts
2. apply labels
3. enter query
4. hit search


https://github.com/FreeTubeApp/FreeTube/assets/73130443/6e017af0-8814-41b8-bcdf-3426fdd8709b

2024-04-30 04:49 UTC, ankitchauhan-aka commented
> Filter not applied when:
> 
> 1. Application starts
> 2. apply labels
> 3. enter query
> 4. hit search
> 
>  VirtualBoxVM_E7hDKoPbOO.mp4
**Fixed.**

Thanks for the review.

2024-04-30 06:26 UTC, PikachuEXE commented
It reset filters under strange conditions (e.g. like changing filter below

https://github.com/FreeTubeApp/FreeTube/assets/1018543/b29fa63c-bf96-4fd6-b632-6c5be57e189e

Probably like
- Search A
- Enter B
- Try to set multiple criteria

2024-04-30 06:42 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@PikachuEXE this is not a bug but intended behavior. There is how YT also behaves. In your example Time Today resets because you clicked on Type Channel. Time is based on upload date. A channel cant have a upload date.

2024-04-30 09:02 UTC, PikachuEXE approved these changes
OK there are several issue discovered during testing but not introduced by this PR

2024-04-30 10:27 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Issue?

2024-04-30 10:59 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2024-05-07 16:33 UTC, ankitchauhan-aka commented
@jasonhenriquez can we get this reviewed.

2024-05-07 17:01 UTC, jasonhenriquez requested changes
Looks like the implementation was changed enough by #3975 to make the required alteration easier. Address review comments, re-validate, and you should be good.

2024-05-07 17:01 UTC, jasonhenriquez commented on src/renderer/components/ft-search-filters/ft-search-filters.vue
> +          :selected="searchSettings.duration"
**suggestion (blocking):** You should be able to remove the `ft-radio-button` and `ft-search-filters` changes altogether once you have implemented the other suggested change.

2024-05-25 21:20 UTC, jasonhenriquez commented
Hi @ankitchauhan-aka, are you still available to make these final alterations?

2024-05-26 05:39 UTC, ankitchauhan-aka commented
Hi @jasonhenriquez 
Yeah. I was too much busy in my job will do it asap

2024-06-02 16:21 UTC, ankitchauhan-aka commented
@jasonhenriquez seems good now!

2024-06-02 16:31 UTC, jasonhenriquez commented
In my testing, it's not actually applying the filters now - the probable issue is that the removal is processing before the results are being grabbed.

2024-06-02 18:22 UTC, ankitchauhan-aka commented
I think that's correct behaviour. It should remove filter if search query is modified.

2024-06-02 20:00 UTC, jasonhenriquez commented
No, I mean it's not applying the filter even the first time.

2024-06-03 16:13 UTC, ankitchauhan-aka commented
https://www.awesomescreenshot.com/video/28282864?key=3f195c5137a0c69969519b2bdf7fe124
@jasonhenriquez Please take a look at the attached video, if you feel that some of the records do not match the time filter, So it's not related to our application logic, Even YouTube has the same results. or if your testing produces different results than mine please share a capture.

2024-06-06 18:56 UTC, ankitchauhan-aka commented
@jasonhenriquez could you please share!

2024-06-06 20:40 UTC, jasonhenriquez commented
Hi @ankitchauhan-aka, sorry for the delay. Just retested now; it was working the first handful of times, then just stopped applying the filter at all.

https://github.com/FreeTubeApp/FreeTube/assets/84899178/4d5c08d3-63a4-43ef-845f-c85deb5db1ab

Before moving forward with this, I'd also like some discussion on the intended behavior. We're showing the filter as active after a search is made, until the user submits another query. That's not intuitive, as we shouldn't be showing the filter as if it's active if it isn't going to be. The main reason YT has this behavior the way it is is because changing a filter setting re-applies the same search but with the filter changed. If we do want this feature, the filters should show as clear immediately after the search processes.

2024-06-09 09:03 UTC, ankitchauhan-aka commented
@jasonhenriquez thanks for the video, I can see the issue in your video but am not able to reproduce it. Did you notice any steps for the issue? Also, I've modified it for the new requirement to clear the filter after search

2024-06-09 12:58 UTC, jasonhenriquez approved these changes
LGTM. The bug that I was encountering was setting a feature filter while a channel was set, which should be fixed by #5197.

2024-06-09 16:19 UTC, ankitchauhan-aka commented
Great can we merge it now?

2024-06-09 16:21 UTC, ankitchauhan-aka commented
@jasonhenriquez great. Hoping to get it merged before we get any conflicts again 😉

2024-06-10 20:30 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
> when u just go to another page lets say most popular the filter also clears.

Taken from the linked issue. This also needs to be implemented.

2024-06-12 16:18 UTC, ankitchauhan-aka commented
> > when u just go to another page lets say most popular the filter also clears.
> 
> Taken from the linked issue. This also needs to be implemented.

Fixed.

2024-06-12 21:20 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
Route is changed, Filters applied correctly but Filter icon isnt active

https://github.com/FreeTubeApp/FreeTube/assets/73130443/b5a0f26a-189d-4d1a-b76f-ba573061fb37

2024-06-12 21:45 UTC, jasonhenriquez commented
@efb4f5ff-1298-471a-8973-3d47447115dc Isn't that the expected behavior? See [my earlier comment](https://github.com/FreeTubeApp/FreeTube/pull/5033#issuecomment-2153371087):

Before moving forward with this, I'd also like some discussion on the intended behavior. We're showing the filter as active after a search is made, until the user submits another query. That's not intuitive, as we shouldn't be showing the filter as if it's active if it isn't going to be. The main reason YT has this behavior the way it is is because changing a filter setting automatically re-submits the same search query but with the new filter. If we do want this feature, the filters should show as clear immediately after the search processes.

2024-06-12 21:52 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Oof i missed that. Will retest soon.

2024-06-13 08:28 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@jasonhenriquez isnt this intuitive? Now the user needs to remember what filter they applied if they want to refine their search more:

1. Apply filter
2. Input search query
3. Hit search
4. Filters reset
5. User has to apply the same filter(s) again + they like to add to refine their search results.

User has to remember what filters they applied in their previous search. That seems like a headache to me.

https://github.com/FreeTubeApp/FreeTube/assets/73130443/f9e13178-69ba-463b-9acf-6145baaf1d36

2024-06-14 15:38 UTC, ankitchauhan-aka commented
@jasonhenriquez so what's next step about this?

2024-06-15 10:46 UTC, ankitchauhan-aka commented
I think we should keep the filters selected until the user is changing search query.

2024-06-15 12:08 UTC, jasonhenriquez commented
If I'm understanding correctly, that means showing it as active for the next search, even if it won't be, unless the user then changes the filter to something else, in which case it will be? That seems a bit confusing if so.

2024-06-15 16:13 UTC, ankitchauhan-aka commented
What if clear filter only if user types different search query

2024-06-15 19:13 UTC, jasonhenriquez commented
If you can get the filter to show as non-active to the user unless they re-open the search filter modal, I'm fine with that. I would also be fine with "have the filters be forgotten unless the user opts to open the modal after a search." I just get the sense that we're trying to emulate YT's behavior here somewhat, which doesn't work exactly, since our filter button is omnipresent, and our current behavior is different. 

I'm also wondering if maybe this is getting too complicated / potentially confusing to users, and maybe we should just have a one-click button that removes all active search filters instead.

2024-07-31 01:42 UTC, closed without merging