Added functionality to export a single playlist
FreeTubeApp/FreeTube pull request #5779
Opened 2024-10-01 16:35 UTC by Zeabyte

# Single Playlist Export

## Pull Request Type

- [ ] Bugfix
- [x] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

closes #5366

## Description

This PR adds a button "Export Playlist" to the playlist-info component, that when clicked exports a single playlist with the file name "freetube-playlist-{playlistName}-{date}.db".

## Screenshots 

After:
![image](https://github.com/user-attachments/assets/0394e283-2cac-4c28-b994-eff51180f959)

## Testing 

I have tested this and found no problems. However, the UX is not perfect because this is only exporting. Importing currently requires going to data settings and there is no "Do you wish to overwrite the playlist" or "... add the videos to the local playlist" with the same name.

## Desktop

- **OS:** Fedora Workstation
- **OS Version:** 40
- **FreeTube version:** latest from development

## Additional context

One could further abstract the way files are saved to disk. I have copied it from data-settings.js.
I have reused the locale token `Settings.Data Settings.Unable to write file`.

2024-10-02 00:58 UTC, PikachuEXE commented on src/renderer/components/playlist-info/playlist-info.js
> +      const title = this.selectedUserPlaylist.playlistName.replaceAll(' ', '-')
IMO spaces are usually replaced with `_` more often then `-`
I think only for SEO (URL) people prefer using `-`
Let me know if that's wrong :)

Also we might need to replace all invalid chars, e.g. `/` on MacOS, different for other OSes
(handling user input is nasty)

![image](https://github.com/user-attachments/assets/d955f900-f215-4143-b3e1-d02d52ea2c02)

```suggestion
      const title = this.selectedUserPlaylist.playlistName.replaceAll(' ', '_')
```

2024-10-07 07:36 UTC, PikachuEXE commented on src/renderer/components/playlist-info/playlist-info.js
> +      const title = this.selectedUserPlaylist.playlistName.replaceAll(' ', '_').replaceAll(/["%*/:<>?\\|]/g, '_')
Might need to replace more chars
See
https://www.mtu.edu/umc/services/websites/writing/characters-avoid/

I use `Special !@#$%^&*()-_=+[]{};:'".>/?\| List` as test name and I got `freetube-playlist-Special_!@#$_^&_()-_=+[]{};_'_.______List-2024-10-07` on MacOS
Need a windows guy to test the result

2024-10-07 09:09 UTC, Zeabyte commented on src/renderer/components/playlist-info/playlist-info.js
> +      const title = this.selectedUserPlaylist.playlistName.replaceAll(' ', '_').replaceAll(/["%*/:<>?\\|]/g, '_')
@PikachuEXE I thought that the characters I listed in the Regexp would be those that are absolutely illegal for use in certain OS’s. The guide you linked calls some absolutely common, usual and legal characters "illegal" and "forbidden". So, just to confirm, this is more about conventions, right?

Thanks for having a look at it.

2024-10-07 10:57 UTC, PikachuEXE commented on src/renderer/components/playlist-info/playlist-info.js
> +      const title = this.selectedUserPlaylist.playlistName.replaceAll(' ', '_').replaceAll(/["%*/:<>?\\|]/g, '_')
I didn't have access to Windows machine so I can't test it
Here is a screenshot of forbidden char message
![2024-10-07 18_55_11-重新命名](https://github.com/user-attachments/assets/26cf73a6-60af-4137-8705-5d79508accb0)

I will create a custom build to test on Windows machine later

2024-10-08 01:56 UTC, PikachuEXE commented on src/renderer/components/playlist-info/playlist-info.js
> +      const title = this.selectedUserPlaylist.playlistName.replaceAll(' ', '_').replaceAll(/["%*/:<>?\\|]/g, '_')
On windows I have `freetube-playlist-Special_!@#$_^&_()-_=+[]{};_'_.______List-2024-10-07.db`, same as MacOS

2024-10-08 01:57 UTC, PikachuEXE submitted a review, later dismissed
I assume Linux is fine

2024-10-10 00:23 UTC, PikachuEXE commented
@efb4f5ff-1298-471a-8973-3d47447115dc @absidue 👋

2024-10-12 07:53 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
- Dont show the export button when playlist has no videos in it.
- Move the export button to right of the green copy playlists button so that all the green and red buttons are grouped correctly
![image](https://github.com/user-attachments/assets/011816b2-7be4-478a-8f89-8a4f8a6519f8)
- Discussion topic: Maybe this closes the issue. I know we dont have a "Import one Playlist button" but now we provide a way to export one playlist. So doesnt that automatically mean that the user can also import one playlist?

2024-10-12 08:03 UTC, PikachuEXE commented
> I know we dont have a "Import one Playlist button" but now we provide a way to export one playlist. So doesnt that automatically mean that the user can also import one playlist?

I think so

2024-10-27 00:58 UTC, PikachuEXE commented
I also see export button on online playlist (which does nothing)
Let me recheck later...

2024-11-03 17:51 UTC, absidue approved these changes

2024-11-04 01:24 UTC, PikachuEXE commented
@ChunkyProgrammer Though I can approve it but if you have time I rather have you take a look :)
Or I will just (partially self-)approve tomorrow

2024-11-04 01:35 UTC, ChunkyProgrammer approved these changes

2024-11-04 01:35 UTC, ChunkyProgrammer commented on src/renderer/components/playlist-info/playlist-info.js
> +      const title = this.selectedUserPlaylist.playlistName.replaceAll(' ', '_').replaceAll(/["%*/:<>?\\|]/g, '_')
Non-blocking: Maybe we should merge the logic here with the logic for replacing the names of files created for screenshots? https://github.com/FreeTubeApp/FreeTube/blob/94fe62aff4c5b721033090a896738bd8006d4c3d/src/renderer/helpers/utils.js#L565

2024-11-04 01:35 UTC, merged