PR ready distraction free feature
FreeTubeApp/FreeTube pull request #596
Opened 2020-10-05 14:30 UTC by tayloraviets

Signed-off-by: Taylor <tayloraviets@gmail.com>

---
Issue #584 "Distraction Free Settings"
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [X] Feature Implementation

**Related issue**
#584 #590 

**Description**
This adds a "Distraction Free Settings" section to settings with the following 8 options:
-Hide Video Views
-Hide Video Likes/Dislikes
-Hide Channel Subscribers
-Hide Comment Likes
-Hide Recommended Videos
-Hide Popular Videos
-Hide Trending Videos
-Hide Live Chat

**Testing (for code that is not small enough to be easily understandable)**
Tested on windows through the UI using the dev_runner script and VS code.
Tested using both the local and invidious player.
Tried to test thoroughly however I am not fully aware of freetube's capabilities as of yet

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - OS Version: 10.0.18362 Build 18362
 - FreeTube version: N/A

**Additional context**
584 called for the hiding comments however since they are pre-collapsed I chose not to include this.

issues noticed during development:
1. subcomment likes do not display when using local API, this bug is present on develop

2. if autoplay is enabled before turning off recommended videos then a video autoplays even when no recommendations are visible. was not able to find a way to stop it that wasn't hacky and/or confusing for the user.

3. streams don't appear to work with the invidious server, this also happens on develop

4. people on youtube who exclusively stream don't appear to have subscribers visible at all (example channel "stocks rocks") which displays as 0 subscribers on their channel page in freetube, technically a visual bug

5. when searching for a channel using the local API subCount isn't populated displaying as 0 subs, this is present in development

2020-10-05 14:31 UTC, tayloraviets commented on src/renderer/components/ft-list-channel/ft-list-channel.js
> +        this.subscriberCount = this.data.followers.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')
this line is the cause of my listed issue number 5. followers doesn't appear to be an accessible field in this scope

2020-10-05 14:33 UTC, tayloraviets commented
working on fixing linter issues

2020-10-05 18:07 UTC, GilgusMaximus commented
PrestoN has to check your code. I am not familiar enough with adding these things to the code base.
However if you want: Could you create issues for the problems you found? If you do not want to, I can create them as well.

2020-10-05 18:11 UTC, tayloraviets commented
@GilgusMaximus I will create issues for the problems I found (assuming they don't exist already) in a few hours when I get off work

2020-10-05 18:27 UTC, PrestonN requested changes
Hey there!  This looks really good actually.  This is more or less how I would have implemented this, so thank you very much!

Please take a look at the comments that I've made.  They're very small changes and should be quick to fix.

Also please fix the remaining linting issues that you have (Except for the one from App.js, that one isn't your fault).

2020-10-05 18:27 UTC, PrestonN commented on static/locales/en-US.yaml
> +    Distraction Settings: Distraction Free Settings
Please have the object key match the English phrase.

2020-10-06 00:48 UTC, PrestonN commented
I apologize.  I didn't address the issues you noticed.  I'll go ahead and do that.

1. We're aware of this.  We'll fix it in a future update.

2. This is a good point, and is something that I thought of as well.  We could probably just display a message that tells the user that the autoplay next video is disabled if they decide to also disable viewing the video recommendations.  You're welcome to include this functionality in this PR or I can work on it once this is merged.  Completely your choice.

3. and 4. Let's make a new issue about this so we can further investigate.

5. I'm aware of this.  Neither the local API or Invidious API returns a proper value, so I may remove this entirely.  You're welcome to remove it in this PR if you'd like.

2020-10-06 01:32 UTC, tayloraviets commented
okay, changes made and linter happy. Sorry for all the commits, took a bit to realize I could just run the linter locally.

as for your comment @PrestonN I will now make issues for points 2, 3, and 4 of my additional context section. I'd normally try to fix the autoplay issue now but I expect to be busy the next few days.

2020-10-06 02:22 UTC, PrestonN requested changes
Please make this last change and we should be good.  I'll handle the remaining issues in the next day or so.

2020-10-06 02:22 UTC, PrestonN commented on src/renderer/store/modules/settings.js
> +              commit('setHideLiveChat, result.value')
This string needs to be fixed.

2020-10-06 02:27 UTC, PrestonN commented
Great!  Thank you so much for this pull request!  I know quite a few people are going to be pleased to see this. :)

Thanks again!

2020-10-06 02:27 UTC, merged