Add local api support for viewing individual community posts + comments
FreeTubeApp/FreeTube pull request #6491
Opened 2024-12-31 20:28 UTC by ChunkyProgrammer

# Add local api support for viewing community posts

## Pull Request Type
- [x] Feature Implementation

## Related issue
closes #3253

## Description
This PR also adds support for viewing community posts + comments to the local API

## Testing
- set local api as primary api
- disable invidious
- go to mr beast channel
- go to community tab
- click on the link to view one of the posts
- load comments
- load comment replies
- load more comments

See tests here: https://github.com/FreeTubeApp/FreeTube/pull/5589

## Desktop
- **OS:** Fedora Linux
- **OS Version:** 41
- **FreeTube version:** latest nightly

2024-12-31 22:31 UTC, absidue reviewed
Doesn't need to be done just yet as this PR is still a draft, but it would be good to remove the now unused "posts are only supported by invidious" string once this is ready for review.

2024-12-31 22:31 UTC, absidue commented on src/renderer/helpers/api/local.js
> +export async function getCommunityPostComments(postId, channelId, sortByNewest) {
Could you please include local in the name, like we do for other functions that this file exports.

2025-01-11 20:33 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Upstream just merged🎉

2025-01-21 06:25 UTC, absidue commented
Full changelog: https://github.com/LuanRT/YouTube.js/releases/tag/v13.0.0

The breaking changes don't affect us, as we use a bundler (webpack) instead of the prebundled files.

This will unblock #6375 and #6491

2025-01-21 22:01 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Error:

https://github.com/user-attachments/assets/e41deb9d-eae9-48e1-aa58-b990664dcdb5

2025-01-22 13:38 UTC, ChunkyProgrammer commented
> Error:
> VirtualBoxVM_2gUbmdP7GZ.mp4

Hmm, weirdly I'm only getting that error on that specific post

2025-01-25 18:11 UTC, absidue reviewed
I've submitted a PR upstream to fix the problem https://github.com/LuanRT/YouTube.js/pull/882

The post params were only being encoded to base64 not URL safe base64, so for that post it contained a `/` which should have been an `_`, which made YouTube return the channel home tab.

2025-01-25 21:59 UTC, absidue commented on src/renderer/views/Post.vue
> -      {{ $t('Channel.Community.Viewing Posts Only Supported By Invidious') }}
Please remove this unused string from at least the en-US file (as I understand it the decision on other PS has essentially boiled down to, removing it from all files causes too many conflicts m, so instead I have to do a follow up every now and then to get rid of them all in one go), that way people won't have to translate a known unused string anymore.

2025-01-27 02:32 UTC, ChunkyProgrammer commented on src/renderer/views/Post.vue
> -      {{ $t('Channel.Community.Viewing Posts Only Supported By Invidious') }}
Sorry, I missed your first comment after the new version of youtube.js was released.
In this case, removing this string shouldn't cause many/any conflicts so it should be fine :smile:

2025-02-26 23:35 UTC, absidue commented
Opening a post link without a channel ID fails, this isn't caused by this PR as it is broken on both backends and the resolve URL response for post URLs seems to have changed on YouTube's end e.g. https://www.youtube.com/post/UgkxtZU_keFi3mw46hCUe9YfhfBHoeR8YCoM

Here is the Innertube `/navigation/resolve_url` response for that URL, params is a weird protobuf that has two field with the channel ID and one field with the post ID.

```json
{
    "responseContext": {},
    "endpoint": {
        "clickTrackingParams": "",
        "commandMetadata": {
            "webCommandMetadata": {
                "url": "/channel/UCBR8-60-B28hp2BmDPdntcQ/community?lb=UgkxtZU_keFi3mw46hCUe9YfhfBHoeR8YCoM",
                "webPageType": "WEB_PAGE_TYPE_BROWSE",
                "rootVe": 247244,
                "apiUrl": "/youtubei/v1/browse"
            }
        },
        "browseEndpoint": {
            "browseId": "FEpost_detail",
            "params": "wgNaEhhVQ0JSOC02MC1CMjhocDJCbURQZG50Y1EaJFVna3h0WlVfa2VGaTNtdzQ2aENVZTlZZmhmQkhvZVI4WUNvTVoYVUNCUjgtNjAtQjI4aHAyQm1EUGRudGNR"
        }
    }
}
```

![protobuf-fields](https://github.com/user-attachments/assets/ddeb8bfb-ce2c-4931-969b-13102e9810e9)

2025-03-18 17:55 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2025-03-19 00:50 UTC, PikachuEXE commented
Images look strange but might not be related to PR

Comments can't be loaded
![image](https://github.com/user-attachments/assets/676ec429-27ac-4be5-96c8-39921589ca01)

2025-03-19 05:49 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@PikachuEXE see #4852

2025-03-30 11:57 UTC, absidue commented
Can confirm that the post link issue is fixed.
As was already mentioned by pika, on some posts the comments don't load at all and for others they fail when sorting. For the sorting issue taking the same approach that we do for sorting the video comments should work (using the sort payloads provided by YouTube instead of making YouTube.js generate it).

2025-04-24 03:02 UTC, ChunkyProgrammer commented
PR opened on YouTube.js: https://github.com/LuanRT/YouTube.js/pull/955

2025-06-03 16:55 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Waiting for https://github.com/LuanRT/YouTube.js/pull/956 to be release

2025-06-09 15:13 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
https://github.com/FreeTubeApp/FreeTube/pull/7542

2025-06-26 04:34 UTC, ChunkyProgrammer commented
Relies on: https://github.com/LuanRT/YouTube.js/pull/987

2025-07-18 18:49 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
relies on https://github.com/FreeTubeApp/FreeTube/pull/7701

2025-07-20 13:57 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes
Im getting some errors

https://github.com/user-attachments/assets/53d5d67f-5a74-48c6-b6c1-ba823760a468


https://github.com/user-attachments/assets/167181d0-f277-4c29-be37-12537643e5e7

2025-07-22 21:15 UTC, ChunkyProgrammer commented
Going to close and reopen this PR without the locale file changes. Seems like weird white space changes are happening

2025-07-22 21:15 UTC, closed without merging