[issue-782] Added goToChannel function to redirect the comment author's channel
FreeTubeApp/FreeTube pull request #850
Opened 2020-12-09 05:30 UTC by eunbeek

---
Title
---

**Important note**
Please note that only PrestoN is able to merge Pull Requests into master.

**Pull Request Type**
Please select what type of pull request this is:
- [ ] Bugfix
- [X ] Feature Implementation

**Related issue**
Please link the issue your pull request is referring to.
#782 

**Description**
Please write a clear and concise description of what the pull request does.

Added the function to redirect the comment author's channel when clicking the thumbnails in the video comment section.
Only two files are changed : 
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/components/watch-video-comments/watch-video-comments.vue

**Screenshots (if appropriate)**
Please add before and after screenshots if there is a visible change.

https://youtu.be/FHSUa8OfgTw

![image](https://user-images.githubusercontent.com/50673489/101588956-80574980-39b5-11eb-9f58-3d7734eedf39.png)
![image](https://user-images.githubusercontent.com/50673489/101588961-84836700-39b5-11eb-91ed-8d2fe9719e74.png)

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Window
 - OS Version: [e.g. 22] 10
 - FreeTube version: [e.g. 0.8]

**Additional context**
Add any other context about the problem here.

2020-12-15 19:45 UTC, PrestonN requested changes
Works just fine. Please make the requested changes and we'll be good to merge. :)

2020-12-15 19:45 UTC, PrestonN commented on src/renderer/components/watch-video-comments/watch-video-comments.vue
>            class="commentThumbnail"
Could you please add `cursor: pointer` to the CSS of this class? We want users to know that this is clickable.

2020-12-15 19:45 UTC, PrestonN commented on src/renderer/components/watch-video-comments/watch-video-comments.vue
>          <p class="commentAuthor">
Please also make this clickable. Apply the same pointer CSS from the author thumbnail as well.

2021-03-18 16:51 UTC, GilgusMaximus commented
Unfortunately the requirements were not met and the code base also changed requiring further changes. Therefore I reimplemented the feature #1126 and fixed the problems this PR now has in the newest FT version

2021-03-18 16:51 UTC, closed without merging